#!/usr/bin/env python
#

import sys
import os

# file_load
#
def file_load(file_name):
    """
    Load the indicated file into a string and return the string.
    """

    retval = None
    if os.path.exists(file_name):
        with open(file_name, 'r') as f:
            retval = f.read()
    else:
        sys.stderr.write("  ** Warning: The requested file (%s) does not exist.\n" % file_name)

    return retval

def main(argv):

    if (len(argv) > 0):
       print("<testsuites>")
       for fname in argv[0:]:
           content = file_load(fname).split('\n')
           for line in content[1:-2]:
               print(line)
       print("</testsuites>")
    else:
        print("No files specified on the command line.")

if __name__ == '__main__':
    main(sys.argv[1:])

# vi:set ts=4 sw=4 expandtab:
