/* this file is automatically generated */
#include <linux/netdevice.h>
static inline void netif_poll_enable(struct net_device *dev) {}
static inline void netif_poll_disable(struct net_device *dev) {}
#include <linux/percpu.h>
#define proc_net_root init_net.proc_net
