/* automatically generated from hal.c */
#ifdef CONFIG_X86_64

WIN_FUNC_DECL(KefAcquireSpinLockAtDpcLevel, 1)
WIN_FUNC_DECL(KefReleaseSpinLockFromDpcLevel, 1)
WIN_FUNC_DECL(KeGetCurrentIrql, 0)
WIN_FUNC_DECL(KeStallExecutionProcessor, 1)
WIN_FUNC_DECL(KfAcquireSpinLock, 1)
WIN_FUNC_DECL(KfLowerIrql, 1)
WIN_FUNC_DECL(KfRaiseIrql, 1)
WIN_FUNC_DECL(KfReleaseSpinLock, 2)
WIN_FUNC_DECL(READ_PORT_BUFFER_ULONG, 3)
WIN_FUNC_DECL(READ_PORT_BUFFER_USHORT, 3)
WIN_FUNC_DECL(READ_PORT_UCHAR, 1)
WIN_FUNC_DECL(READ_PORT_ULONG, 1)
WIN_FUNC_DECL(READ_PORT_USHORT, 1)
WIN_FUNC_DECL(READ_REGISTER_USHORT, 1)
WIN_FUNC_DECL(WRITE_PORT_BUFFER_ULONG, 3)
WIN_FUNC_DECL(WRITE_PORT_BUFFER_USHORT, 3)
WIN_FUNC_DECL(WRITE_PORT_UCHAR, 2)
WIN_FUNC_DECL(WRITE_PORT_ULONG, 2)
WIN_FUNC_DECL(WRITE_PORT_USHORT, 2)
WIN_FUNC_DECL(WRITE_REGISTER_UCHAR, 2)
WIN_FUNC_DECL(WRITE_REGISTER_ULONG, 2)
WIN_FUNC_DECL(WRITE_REGISTER_USHORT, 2)
#endif
struct wrap_export hal_exports[] = {
   
   WIN_SYMBOL(KefAcquireSpinLockAtDpcLevel,1),
   WIN_SYMBOL(KefReleaseSpinLockFromDpcLevel,1),
   WIN_SYMBOL(KeGetCurrentIrql,0),
   WIN_SYMBOL(KeStallExecutionProcessor,1),
   WIN_SYMBOL(KfAcquireSpinLock,1),
   WIN_SYMBOL(KfLowerIrql,1),
   WIN_SYMBOL(KfRaiseIrql,1),
   WIN_SYMBOL(KfReleaseSpinLock,2),
   WIN_SYMBOL(READ_PORT_BUFFER_ULONG,3),
   WIN_SYMBOL(READ_PORT_BUFFER_USHORT,3),
   WIN_SYMBOL(READ_PORT_UCHAR,1),
   WIN_SYMBOL(READ_PORT_ULONG,1),
   WIN_SYMBOL(READ_PORT_USHORT,1),
   WIN_SYMBOL(READ_REGISTER_USHORT,1),
   WIN_SYMBOL(WRITE_PORT_BUFFER_ULONG,3),
   WIN_SYMBOL(WRITE_PORT_BUFFER_USHORT,3),
   WIN_SYMBOL(WRITE_PORT_UCHAR,2),
   WIN_SYMBOL(WRITE_PORT_ULONG,2),
   WIN_SYMBOL(WRITE_PORT_USHORT,2),
   WIN_SYMBOL(WRITE_REGISTER_UCHAR,2),
   WIN_SYMBOL(WRITE_REGISTER_ULONG,2),
   WIN_SYMBOL(WRITE_REGISTER_USHORT,2),
   {NULL, NULL}
};
