#!/bin/bash

exit_val=0;

# Add a signed-off-by if it doesn't exist
SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# Catch duplicates
test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 "E: Duplicate Signed-off-by lines."
	echo >&2
	exit_val=1
}

# Check for proper UBUNTU: usage. A few rules:
# * ^UBUNTU must be one first line
# * '#' lines are comments, so can be ignored
# * There must be a space after UBUNTU:
# * There must be a message following that space
if ! (grep -v '^#' "$1" | head -1 | egrep -q '^UBUNTU: [^ ]+'); then
	if [ "`git-config --bool ubuntu.allow-non-ubuntu-commit`" = "true" ]; then
		echo >&2 "W: Override enforced by ubuntu.allow-non-ubuntu-commit"
	else
		echo >&2 "E: Commit message doesn't start with UBUNTU:, or is empty"
		echo >&2 "   To override: git-config --bool ubuntu.allow-non-ubuntu-commit true"
		exit_val=1
	fi
	echo >&2
fi

# Similar to above, except we want a SAUCE commit for non ubuntu/debian
# files (anything from stock kernel tree). Note that the pre-commit check
# will verify that we are not comitting ubuntu/debian stuff along with
# changes to the kernel.
if (git-diff-index -M --name-only --cached HEAD | egrep -v '^(ubuntu|debian)/'); then
	if ! (grep -v '^#' "$1" | head -1 | egrep -q '^UBUNTU: SAUCE: [^ ]+'); then
		if [ "`git-config --bool ubuntu.allow-non-sauce-commit`" = "true" ]; then
			echo >&2 "W: Override enforced by ubuntu.allow-non-sauce-commit"
		else
			echo >&2 "E: In-kernel commit message doesn't contain SAUCE in msg"
			echo >&2 "   To override: git-config --bool ubuntu.allow-non-sauce-commit true"
			exit_val=1
		fi
		echo >&2
	fi
fi

exit $exit_val
