#!/bin/bash

# This will set all overrides to false after a successful commit, so they
# aren't persistent

tokens="flavour-changes-ok others-changes-ok config-desync-ok allow-non-ubuntu-commit"

for tok in $tokens; do
	git-config --bool ubuntu.$tok false
done
