#!/bin/bash

clear
date -R

ARGS=""
while [ $# != 0 ]; do
	case "$1" in
		-a|-v)
			ARGS="$1 $ARGS"
			shift
			;;
		*)
			break
			;;
	esac
done

export BUILD_DIST_PRINTED=1
while true; do
	START=$(date +%s)
	if [ "$1" = '' ]; then
		INFO=$($(dirname $0)/build-status-all $ARGS 2>&1)
	else
		INFO=$($(dirname $0)/build-status $ARGS $@ 2>&1)
		sleep 3
	fi
	clear
	date -R
	echo "$INFO"
	STOP="$(date +%s)"

	let "STOP=30-(STOP-START)"
	if [ ${STOP} -gt 0 ]; then
		sleep ${STOP}
	fi
done
