#!/bin/bash
. $(dirname $0)/build-common

if [ "$1" = "" ]; then
	echo "Usage: $0 <system>"
	exit 1
fi

GetHostEnvironment $1
if [ "$CONCURRENCY" = "" ]; then
	CONCURRENCY=4
fi

status=$($(dirname $0)/build-check ${SYSNAME})

if [ "$status" != "idle" ]; then
	printf "%-15s: $status\n" ${SYSNAME}
	exit 1
fi

case ${BASEDIR} in
	/home/*|home/*)
		TGTDIR="${BASEDIR}"
		;;
	*)
		TGTDIR="$(GetChrootLocation ${HOST} ${CHROOT})${BASEDIR}"
		;;
esac

EmitDoBuild $CONCURRENCY | ssh ${HOST} \
	"cd $TGTDIR && cat - >do-build && chmod 700 do-build"
ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/do-build
printf "%-15s: build started\n" $SYSNAME
