#!/bin/bash
. $(dirname $0)/build-common

if [ "$1" = "" ]; then
	echo "Usage: $0 <system>"
	exit 1
fi

GetHostEnvironment $1
if [ "$CONCURRENCY" = "" ]; then
	CONCURRENCY=4
fi

status=$($(dirname $0)/build-check ${SYSNAME})
if [ $? -ne 0 ]; then
	printf "%-15s: $status\n" ${SYSNAME}
	exit 1
fi

EmitDoBuild $CONCURRENCY | ssh ${HOST} \
	"cd $BASEDIR 2>/dev/null && cat - >do-build && chmod 700 do-build"
if [ $? -eq 0 ]; then
	ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/do-build ${BUILDTARGET}
	printf "%-15s: ${BUILDTARGET} build started\n" $SYSNAME
else
	printf "%-15s: %s not found\n" $SYSNAME $BASEDIR
fi
