#!/bin/bash

. ~/bin/build-common

if [ "$system" = "" ]; then
	echo "Usage: $0 <system>"
	exit 1
fi

status=$(build-check $system)

if [ $status = "building" ]; then
	ssh $system killall screen > /dev/null 2>&1
	printf "%-15s: stopped\n" $system
else
	printf "%-15s: $status\n" $system
fi
