#!/bin/bash

export BUILD_DIST_PRINTED=1
. $(dirname $0)/build-common

if [ "$1" = "" ]; then
        echo "Usage: $(basename $0) <system>"
        exit 1
fi

GetHostEnvironment $1 || exit 1

ssh -oConnectTimeout=5 $HOST test -f $BUILDING >/dev/null 2>&1
case $? in
	0)
		echo building
		exit 1
		;;
	1)
		echo idle
		;;
	*)
		echo ${HOST} is offline
		exit 1
		;;
esac

exit 0
