#!/bin/bash
. $(dirname $0)/build-common

ARGS=""
if $VERBOSE; then
	ARGS="-v"
fi

if [ "$1" = "" ]; then
	echo "Usage: $0 [-v] <system> [systems ...]"
	exit 1
fi

while [ "$1" != "" ]; do
	GetHostEnvironment $1
	shift
	if [ $? -ne 0 ]; then
		continue
	fi

	PREFIX="$SYSNAME"
	ssh $HOST "cd $BASEDIR && ./run-status $ARGS" | while read LINE; do
		printf "%-15s %s\n" "$PREFIX" "$LINE"
		PREFIX=""
	done
done
