#!/usr/bin/env python
#

import socket
from sys  import argv, exit

if (len(argv) < 4):
   print "Usage: %s loghost portno message to be inserted in log" % argv[0]
   exit()

HOST, PORT = argv[1], int(argv[2])
data = " ".join(argv[2:])

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

sock.sendto(data + "\n", (HOST, PORT))
