#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated C config: don't edit
 * Sun Aug 10 13:05:10 IDT 2008 
 * compat-wireless-2.6: v4.5-7-g727c749
 * linux-2.6: iwlwifi-2.3.5
 */
#define COMPAT_RELEASE "v4.5-7-g727c749"
#define COMPAT_KERNEL_RELEASE "iwlwifi-2.3.5"
#if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,21))
#error Compat-wireless requirement: Linux >= 2,6,21
#endif /* (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,21) */ 
#ifndef CONFIG_WIRELESS_EXT
#error Compat-wireless requirement: CONFIG_WIRELESS_EXT must be enabled in your kernel
#endif /* CONFIG_WIRELESS_EXT */
#ifndef CONFIG_MAC80211
#define CONFIG_MAC80211 1
#endif /* CONFIG_MAC80211 */ 
#ifndef CONFIG_MAC80211_DEBUG
#define CONFIG_MAC80211_DEBUG 1
#endif /* CONFIG_MAC80211_DEBUG */ 
#ifndef CONFIG_MAC80211_LEDS
#define CONFIG_MAC80211_LEDS 1
#endif /* CONFIG_MAC80211_LEDS */ 
#ifndef CONFIG_MAC80211_DEBUGFS
#define CONFIG_MAC80211_DEBUGFS 1
#endif /* CONFIG_MAC80211_DEBUGFS */ 
#ifndef CONFIG_MAC80211_RC_DEFAULT
#define CONFIG_MAC80211_RC_DEFAULT "pid"
#endif /* CONFIG_MAC80211_RC_DEFAULT */ 
#ifndef CONFIG_MAC80211_RC_PID
#define CONFIG_MAC80211_RC_PID 1
#endif /* CONFIG_MAC80211_RC_PID */ 
#ifndef CONFIG_MAC80211_MESH
#define CONFIG_MAC80211_MESH 1
#endif /* CONFIG_MAC80211_MESH */ 
#ifndef CONFIG_CFG80211
#define CONFIG_CFG80211 1
#endif /* CONFIG_CFG80211 */ 
#ifndef CONFIG_NL80211
#define CONFIG_NL80211 1
#endif /* CONFIG_NL80211 */ 
#ifndef CONFIG_ATH5K
#define CONFIG_ATH5K 1
#endif /* CONFIG_ATH5K */ 
#ifndef CONFIG_ATH5K_DEBUG
#endif /* CONFIG_ATH5K_DEBUG */ 
#ifndef CONFIG_IWLWIFI
#define CONFIG_IWLWIFI 1
#endif /* CONFIG_IWLWIFI */ 
#ifndef CONFIG_IWLCORE
#define CONFIG_IWLCORE 1
#endif /* CONFIG_IWLCORE */ 
#ifndef CONFIG_IWL3945
#define CONFIG_IWL3945 1
#endif /* CONFIG_IWL3945 */ 
#ifndef CONFIG_IWL4965
#define CONFIG_IWL4965 1
#endif /* CONFIG_IWL4965 */ 
#ifndef CONFIG_IWLAGN
#define CONFIG_IWLAGN 1
#endif /* CONFIG_IWLAGN */ 
#ifndef CONFIG_IWLAGN_LEDS
#define CONFIG_IWLAGN_LEDS 1
#endif /* CONFIG_IWLAGN_LEDS */ 
#ifndef CONFIG_IWLAGN_SPECTRUM_MEASUREMENT
#define CONFIG_IWLAGN_SPECTRUM_MEASUREMENT 1
#endif /* CONFIG_IWLAGN_SPECTRUM_MEASUREMENT */ 
#ifndef CONFIG_IWLWIFI_DEBUG
#define CONFIG_IWLWIFI_DEBUG 1
#endif /* CONFIG_IWLWIFI_DEBUG */ 
#ifndef CONFIG_IWLWIFI_DEBUGFS
#define CONFIG_IWLWIFI_DEBUGFS 1
#endif /* CONFIG_IWLWIFI_DEBUGFS */ 
#ifndef CONFIG_IWLWIFI_LEDS
#define CONFIG_IWLWIFI_LEDS 1
#endif /* CONFIG_IWLWIFI_LEDS */ 
#ifndef CONFIG_IWLWIFI_RFKILL
#define CONFIG_IWLWIFI_RFKILL 1
#endif /* CONFIG_IWLWIFI_RFKILL */ 
#ifndef CONFIG_IWL3945_LEDS
#define CONFIG_IWL3945_LEDS 1
#endif /* CONFIG_IWL3945_LEDS */ 
#ifndef CONFIG_IWL5000
#define CONFIG_IWL5000 1
#endif /* CONFIG_IWL5000 */ 
#ifndef CONFIG_B43
#define CONFIG_B43 1
#endif /* CONFIG_B43 */ 
#ifndef CONFIG_B43_PCMCIA
#define CONFIG_B43_PCMCIA 1
#endif /* CONFIG_B43_PCMCIA */ 
#ifndef CONFIG_B43_DMA
#define CONFIG_B43_DMA 1
#endif /* CONFIG_B43_DMA */ 
#ifndef CONFIG_B43_PIO
#define CONFIG_B43_PIO 1
#endif /* CONFIG_B43_PIO */ 
#ifndef CONFIG_SSB_BLOCKIO
#define CONFIG_SSB_BLOCKIO 1
#endif /* CONFIG_SSB_BLOCKIO */ 
#ifndef CONFIG_B43_DMA_AND_PIO_MODE
#define CONFIG_B43_DMA_AND_PIO_MODE 1
#endif /* CONFIG_B43_DMA_AND_PIO_MODE */ 
#ifndef CONFIG_B43_PCI_AUTOSELECT
#define CONFIG_B43_PCI_AUTOSELECT 1
#endif /* CONFIG_B43_PCI_AUTOSELECT */ 
#ifndef CONFIG_B43_PCICORE_AUTOSELECT
#define CONFIG_B43_PCICORE_AUTOSELECT 1
#endif /* CONFIG_B43_PCICORE_AUTOSELECT */ 
#ifndef CONFIG_B43_LEDS
#define CONFIG_B43_LEDS 1
#endif /* CONFIG_B43_LEDS */ 
#ifndef CONFIG_B43LEGACY
#define CONFIG_B43LEGACY 1
#endif /* CONFIG_B43LEGACY */ 
#ifndef CONFIG_B43LEGACY_PCI_AUTOSELECT
#define CONFIG_B43LEGACY_PCI_AUTOSELECT 1
#endif /* CONFIG_B43LEGACY_PCI_AUTOSELECT */ 
#ifndef CONFIG_B43LEGACY_PCICORE_AUTOSELECT
#define CONFIG_B43LEGACY_PCICORE_AUTOSELECT 1
#endif /* CONFIG_B43LEGACY_PCICORE_AUTOSELECT */ 
#ifndef CONFIG_B43LEGACY_DMA
#define CONFIG_B43LEGACY_DMA 1
#endif /* CONFIG_B43LEGACY_DMA */ 
#ifndef CONFIG_B43LEGACY_PIO
#define CONFIG_B43LEGACY_PIO 1
#endif /* CONFIG_B43LEGACY_PIO */ 
#ifndef CONFIG_B43LEGACY_DMA_AND_PIO_MODE
#define CONFIG_B43LEGACY_DMA_AND_PIO_MODE 1
#endif /* CONFIG_B43LEGACY_DMA_AND_PIO_MODE */ 
#ifndef CONFIG_IPW2100
#define CONFIG_IPW2100 1
#endif /* CONFIG_IPW2100 */ 
#ifndef CONFIG_IPW2100_MONITOR
#define CONFIG_IPW2100_MONITOR 1
#endif /* CONFIG_IPW2100_MONITOR */ 
#ifndef CONFIG_IPW2200
#define CONFIG_IPW2200 1
#endif /* CONFIG_IPW2200 */ 
#ifndef CONFIG_IPW2200_MONITOR
#define CONFIG_IPW2200_MONITOR 1
#endif /* CONFIG_IPW2200_MONITOR */ 
#ifndef CONFIG_IPW2200_RADIOTAP
#define CONFIG_IPW2200_RADIOTAP 1
#endif /* CONFIG_IPW2200_RADIOTAP */ 
#ifndef CONFIG_IPW2200_PROMISCUOUS
#define CONFIG_IPW2200_PROMISCUOUS 1
#endif /* CONFIG_IPW2200_PROMISCUOUS */ 
#ifndef CONFIG_IPW2200_QOS
#define CONFIG_IPW2200_QOS 1
#endif /* CONFIG_IPW2200_QOS */ 
#ifndef CONFIG_P54_PCI
#define CONFIG_P54_PCI 1
#endif /* CONFIG_P54_PCI */ 
#ifndef CONFIG_SSB_PCIHOST_POSSIBLE
#define CONFIG_SSB_PCIHOST_POSSIBLE 1
#endif /* CONFIG_SSB_PCIHOST_POSSIBLE */ 
#ifndef CONFIG_SSB_PCIHOST
#define CONFIG_SSB_PCIHOST 1
#endif /* CONFIG_SSB_PCIHOST */ 
#ifndef CONFIG_SSB_DRIVER_PCICORE_POSSIBLE
#define CONFIG_SSB_DRIVER_PCICORE_POSSIBLE 1
#endif /* CONFIG_SSB_DRIVER_PCICORE_POSSIBLE */ 
#ifndef CONFIG_SSB_DRIVER_PCICORE
#define CONFIG_SSB_DRIVER_PCICORE 1
#endif /* CONFIG_SSB_DRIVER_PCICORE */ 
#ifndef CONFIG_SSB_B43_PCI_BRIDGE
#define CONFIG_SSB_B43_PCI_BRIDGE 1
#endif /* CONFIG_SSB_B43_PCI_BRIDGE */ 
#ifndef CONFIG_RTL8180
#define CONFIG_RTL8180 1
#endif /* CONFIG_RTL8180 */ 
#ifndef CONFIG_ADM8211
#define CONFIG_ADM8211 1
#endif /* CONFIG_ADM8211 */ 
#ifndef CONFIG_RT2X00_LIB_PCI
#define CONFIG_RT2X00_LIB_PCI 1
#endif /* CONFIG_RT2X00_LIB_PCI */ 
#ifndef CONFIG_RT2400PCI
#define CONFIG_RT2400PCI 1
#endif /* CONFIG_RT2400PCI */ 
#ifndef CONFIG_RT2500PCI
#define CONFIG_RT2500PCI 1
#endif /* CONFIG_RT2500PCI */ 
#ifndef CONFIG_RT61PCI
#define CONFIG_RT61PCI 1
#endif /* CONFIG_RT61PCI */ 
#ifndef CONFIG_EEPROM_93CX6
#define CONFIG_EEPROM_93CX6 1
#endif /* CONFIG_EEPROM_93CX6 */ 
#ifndef CONFIG_ZD1211RW
#define CONFIG_ZD1211RW 1
#endif /* CONFIG_ZD1211RW */ 
#ifndef CONFIG_USB_ATMEL
#define CONFIG_USB_ATMEL 1
#endif /* CONFIG_USB_ATMEL */ 
#ifdef CONFIG_USB_NET_CDCETHER
#ifndef CONFIG_USB_NET_RNDIS_HOST
#define CONFIG_USB_NET_RNDIS_HOST 1
#endif /* CONFIG_USB_NET_RNDIS_HOST */ 
#else
#ifndef COMPAT_WARN_CONFIG_USB_NET_RNDIS_HOST
#define COMPAT_WARN_CONFIG_USB_NET_RNDIS_HOST
#endif /* CONFIG_USB_NET_RNDIS_HOST */
#endif /* COMPAT_WARN_CONFIG_USB_NET_RNDIS_HOST */
#ifdef CONFIG_USB_NET_CDCETHER
#ifndef CONFIG_USB_NET_RNDIS_WLAN
#define CONFIG_USB_NET_RNDIS_WLAN 1
#endif /* CONFIG_USB_NET_RNDIS_WLAN */ 
#else
#ifndef COMPAT_WARN_CONFIG_USB_NET_RNDIS_WLAN
#define COMPAT_WARN_CONFIG_USB_NET_RNDIS_WLAN
#endif /* CONFIG_USB_NET_RNDIS_WLAN */
#endif /* COMPAT_WARN_CONFIG_USB_NET_RNDIS_WLAN */
#ifndef CONFIG_USB_NET_CDCETHER
#define CONFIG_USB_NET_CDCETHER 1
#endif /* CONFIG_USB_NET_CDCETHER */ 
#ifndef CONFIG_P54_USB
#define CONFIG_P54_USB 1
#endif /* CONFIG_P54_USB */ 
#ifndef CONFIG_RTL8187
#define CONFIG_RTL8187 1
#endif /* CONFIG_RTL8187 */ 
#ifndef CONFIG_RT2500USB
#define CONFIG_RT2500USB 1
#endif /* CONFIG_RT2500USB */ 
#ifndef CONFIG_RT2X00_LIB_USB
#define CONFIG_RT2X00_LIB_USB 1
#endif /* CONFIG_RT2X00_LIB_USB */ 
#ifndef CONFIG_RT73USB
#define CONFIG_RT73USB 1
#endif /* CONFIG_RT73USB */ 
#ifndef CONFIG_RT2X00
#define CONFIG_RT2X00 1
#endif /* CONFIG_RT2X00 */ 
#ifndef CONFIG_RT2X00_LIB
#define CONFIG_RT2X00_LIB 1
#endif /* CONFIG_RT2X00_LIB */ 
#ifndef CONFIG_RT2X00_LIB_FIRMWARE
#define CONFIG_RT2X00_LIB_FIRMWARE 1
#endif /* CONFIG_RT2X00_LIB_FIRMWARE */ 
#ifndef CONFIG_P54_COMMON
#define CONFIG_P54_COMMON 1
#endif /* CONFIG_P54_COMMON */ 
#ifndef CONFIG_SSB_POSSIBLE
#define CONFIG_SSB_POSSIBLE 1
#endif /* CONFIG_SSB_POSSIBLE */ 
#ifndef CONFIG_SSB
#define CONFIG_SSB 1
#endif /* CONFIG_SSB */ 
#ifndef CONFIG_SSB_SPROM
#define CONFIG_SSB_SPROM 1
#endif /* CONFIG_SSB_SPROM */ 
#ifndef CONFIG_SSB_PCMCIAHOST
#define CONFIG_SSB_PCMCIAHOST 1
#endif /* CONFIG_SSB_PCMCIAHOST */ 
#ifndef CONFIG_SSB_DRIVER_MIPS
#endif /* CONFIG_SSB_DRIVER_MIPS */ 
#ifndef CONFIG_SSB_PCICORE_HOSTMODE
#endif /* CONFIG_SSB_PCICORE_HOSTMODE */ 
#ifndef CONFIG_LIBERTAS_USB
#define CONFIG_LIBERTAS_USB 1
#endif /* CONFIG_LIBERTAS_USB */ 
#ifndef CONFIG_LIBERTAS_CS
#define CONFIG_LIBERTAS_CS 1
#endif /* CONFIG_LIBERTAS_CS */ 
#ifndef CONFIG_LIBERTAS
#define CONFIG_LIBERTAS 1
#endif /* CONFIG_LIBERTAS */ 
#ifndef CONFIG_IEEE80211
#define CONFIG_IEEE80211 1
#endif /* CONFIG_IEEE80211 */ 
#ifndef CONFIG_IEEE80211_CRYPT_CCMP
#define CONFIG_IEEE80211_CRYPT_CCMP 1
#endif /* CONFIG_IEEE80211_CRYPT_CCMP */ 
#ifndef CONFIG_IEEE80211_CRYPT_TKIP
#define CONFIG_IEEE80211_CRYPT_TKIP 1
#endif /* CONFIG_IEEE80211_CRYPT_TKIP */ 
#ifndef CONFIG_IEEE80211_CRYPT_WEP
#define CONFIG_IEEE80211_CRYPT_WEP 1
#endif /* CONFIG_IEEE80211_CRYPT_WEP */ 
#ifndef CONFIG_IEEE80211_SOFTMAC
#endif /* CONFIG_IEEE80211_SOFTMAC */ 
#ifdef CONFIG_NET_SCHED
#ifdef CONFIG_NETDEVICES_MULTIQUEUE
#ifndef CONFIG_MAC80211_QOS
#define CONFIG_MAC80211_QOS 1
#endif /* CONFIG_MAC80211_QOS */ 
#endif
#endif
#endif /* COMPAT_AUTOCONF_INCLUDED */
