#!/usr/bin/python

# This utility updates the relevant bug entries in a database. The database
# entries have a "tasks" attribute that is a list of the update tasks to be
# performed on the database document.
#

from ireport.main                   import Ireport

if __name__ == '__main__':
    app = Ireport()
    app.main()

# vi:set ts=4 sw=4 expandtab:
