#!/bin/bash

# Given an input file name, apply as a patch
# to all of the flattened custom binary source trees.
#
# Ex: debian/scripts/misc/apply-patch-to-binary-custom 0001-sound-oss-remove-offset-from-load_patch-callbacks.patch
#

if [ -z "$1" ] ; then
	echo usage: $0 PATCH_FILE
	exit 1
fi
if [ ! -f $1 ] ; then
	echo $1 does not exit.
	exit 1
fi

for i in debian/binary-custom.d/*/src
do
	patch -p1 -d $i < $1
done

