#!/usr/bin/env python
#
# A script for processing all the "New" bugs.
#

from core.bug_engine                    import BugEngine
from core.dbg                           import Dbg

import bug_handlers.new  # This imports all the bug handler plugins that this script
                         # will use.

# ProcNewBugs
#
class ProcNewBugs(BugEngine):
    """
    This class is all about working on any "New" bugs. "New" bugs
    have a status of: "New".
    """

    # __init__
    #
    def __init__(self):
        """
        The most important things we do here are set the default for the configuration
        file that this script uses and then calls the base class to initialize it.
        """
        defaults = {}
        defaults['configuration_file'] = 'new.rc'
        defaults['launchpad_client_name'] = 'lpltk.kernel.ProcNewBugs'
        BugEngine.__init__(self, defaults)

if __name__ == '__main__':
    Dbg.levels = ['verbose', 'what', 'why', 'vbi']
    app = ProcNewBugs()
    app.main()

# vi:set ts=4 sw=4 expandtab:

