#!/usr/bin/env python
#
# A script for processing all the "New" bugs.
#

from core.bug_engine                    import BugEngine

import bug_handlers.new  # This imports all the bug handler plugins that this script
                         # will use.

# NewEngine
#
class NewEngine(BugEngine):
    """
    This class is all about working on any "New" bugs. "New" bugs
    have a status of: "New".
    """

    # __init__
    #
    def __init__(self):
        """
        The most important things we do here are set the default for the configuration
        file that this script uses and then calls the base class to initialize it.
        """
        defaults = {}
        defaults['configuration_file'] = 'new.rc'
        BugEngine.__init__(self, defaults)

if __name__ == '__main__':
    app = NewEngine()
    app.main()

# vi:set ts=4 sw=4 expandtab:

