#!/usr/bin/env python
#

from core.bug_engine                    import BugEngine

import bug_handlers.open  # This imports all the bug handler plugins that this script
                          # will use.

# OpenEngine
#
class OpenEngine(BugEngine):
    """
    This class is all about working on any "Open" bugs. "Open" bugs
    have a status of: "New", "Confirmed", "Triaged" or "In Progress".
    """

    # __init__
    #
    def __init__(self):
        """
        The most important things we do here are set the default for the configuration
        file that this script uses and then calls the base class to initialize it.
        """
        defaults = {}
        defaults['configuration_file'] = 'open.rc'
        BugEngine.__init__(self, defaults)

if __name__ == '__main__':
    app = OpenEngine()
    app.main()

# vi:set ts=4 sw=4 expandtab:

