#!/bin/bash

date2stamp () {
    date --utc --date "$1" +%s
}

dateDiff (){
    case $1 in
        -s)   sec=1;      shift;;
        -m)   sec=60;     shift;;
        -h)   sec=3600;   shift;;
        -d)   sec=86400;  shift;;
        *)    sec=86400;;
    esac
    dte1=$(date2stamp $1)
    dte2=$(date2stamp $2)
    diffSec=$((dte2-dte1))
    if ((diffSec < 0)); then abs=-1; else abs=1; fi
    echo $((diffSec/sec*abs))
}

LASTRUN=`head -1 /home/kernel/public_html/reports/kt-meeting.txt | cut -f3 -d' '`
TODAY=`date +%F`
DURATION=`dateDiff -d $LASTRUN $TODAY`
if [ $DURATION -ge 7 ]; then
	cd /home/kernel/kteam-tools/irc-meeting
	python kt-meeting-stats.py > /home/kernel/public_html/reports/kt-meeting.txt
fi
