#!/usr/bin/env python
#

from sys                                import argv
from getopt                             import getopt, GetoptError
from ktl.utils                          import stdo, error
from ktl.std_app                        import StdApp
from lpltk.LaunchpadService             import LaunchpadService
from ktl.ubuntu                         import Ubuntu
import sys, os
common_lib = os.path.dirname(os.path.abspath(sys.argv[0]))
common_lib = os.path.dirname(common_lib)
common_lib = os.path.join(common_lib, "lib")
sys.path.insert(0, common_lib)
from buildenv_lib                       import GetUploadVersion

# This script check for component mismatches using the launchpad api

# CmdlineError
#
# The type of exception that will be raised by Cmdline.process() if there
# are command line processing errors.
#
class CmdlineError(Exception):
    # __init__
    #
    def __init__(self, error):
        self.msg = error

# Cmdline
#
class Cmdline:
    """
    Handle all the command line processing for the application.
    """
    # __init__
    #
    def __init__(self):
        self.cfg = {}

    # error
    #
    def error(self, e, defaults):
        """
        Simple helper which prints out an error message and then prints out the usage.
        """
        if e != '': error(e)
        self.usage(defaults)

    # usage
    #
    def usage(self, defaults):
        """
        Prints out the help text which explains the command line options.
        """
        stdo("    Usage:                                                                                   \n")
        stdo("        %s <series> <package>                                                                \n" % self.cfg['app_name'])
        stdo("                                                                                             \n")
        stdo("    Options:                                                                                 \n")
        stdo("        --help           Prints this text.                                                   \n")
        stdo("                                                                                             \n")
        stdo("        --staging                                                                            \n")
        stdo("                         Use the staging LP service instead of the production one.           \n")
        stdo("                                                                                             \n")
        stdo("        --component=<component>                                                              \n")
        stdo("                         Use the specified component instead of the default (main)           \n")
        stdo("                                                                                             \n")
        stdo("        --pocket=<pocket>                                                                    \n")
        stdo("                         Use the specified pocket instead of the default (proposed)          \n")
        stdo("                                                                                             \n")
        stdo("        --pocket_version=<version>                                                           \n")
        stdo("                         Don't check the archive, just use the specified pocket version      \n")
        stdo("                                                                                             \n")
        stdo("    Examples:                                                                                \n")
        stdo("        %s oneiric linux                                                                     \n" % self.cfg['app_name'])

    # process
    #
    def process(self, argv, defaults):
        """
        This method is responsible for calling the getopt function to process the command
        line. All parameters are processed into class variables for use by other methods.
        """
        self.cfg['app_name'] = argv[0]
        result = True
        try:
            optsShort = ''
            optsLong  = ['help', 'staging', 'component=', 'pocket=', 'pocket_version=']
            opts, args = getopt(argv[1:], optsShort, optsLong)

            for opt, val in opts:
                if (opt == '--help'):
                    raise CmdlineError('')

                elif (opt == '--staging'):
                    self.cfg['staging'] = True

                elif opt in '--component':
                    self.cfg['component'] = val

                elif opt in '--pocket':
                    self.cfg['pocket'] = val

                elif opt in '--pocket_version':
                    self.cfg['pocket_version'] = val

            if len(args) < 2:
                raise CmdlineError('Missing series and/or package arguments')
            self.cfg['series'] = args[0]
            self.cfg['package'] = args[1]

        except GetoptError, error:
            print(error, defaults)
            raise CmdlineError('')

        return self.cfg

    # verify_options
    #
    def verify_options(self, cfg):
        """
        Used to verify that all required parameters are present and correct.
        """
        return


# CheckComponent
#
class CheckComponent(StdApp):
    # __init__
    #
    def __init__(self):
        StdApp.__init__(self)
        self.defaults = {}

    # initialize
    #
    def initialize(self):
        """
        A separate initialize that we can control when it gets called (not
        when the object is instantiated).
        """
        self.defaults['launchpad_client_name'] = 'kernel-team-check-component'
        if 'staging' in self.cfg:
            self.defaults['launchpad_services_root'] = 'qastaging'
        self.defaults['component'] = 'main'
        self.defaults['pocket'] = 'proposed'
        self.lp = LaunchpadService(self.defaults)
        self.ubuntu = Ubuntu()
        return

    # main
    #
    def main(self):
        cmdline = Cmdline()
        try:
            self.initialize()
            self.merge_config_options(self.defaults, cmdline.process(argv, self.defaults))
            cmdline.verify_options(self.cfg)

            series = self.cfg['series']
            package = self.cfg['package']
            component = self.cfg['component']
            pocket = self.cfg['pocket']
            if not 'pocket_version' in self.cfg:
                pocket_ver = GetUploadVersion(series, package, pocket=pocket)
                if pocket_ver == None:
                    error("No upload of %s for %s is currently available in"
                          " the %s pocket" % (package, series, pocket))
                    sys.exit(1)
            else:
                pocket_ver = self.cfg['pocket_version']
            ubuntu = self.lp.launchpad.distributions["ubuntu"]
            archive = ubuntu.main_archive
            lp_series = ubuntu.getSeries(name_or_version=series)
            ps = archive.getPublishedSources(exact_match=True,
                                             source_name=package,
                                             distro_series=lp_series,
                                             pocket=pocket.title(),
                                             version=pocket_ver)
            if ps:
                src_pkg = ps[0]
                if src_pkg.component_name != component:
                    print("%s %s - is in %s instead of %s" % 
                          (src_pkg.source_package_name,
                           src_pkg.source_package_version,
                           src_pkg.component_name, component))
                for bin_pkg in src_pkg.getPublishedBinaries():
                    if bin_pkg.component_name != component:
                        print("%s %s - is in %s instead of %s" % 
                              (bin_pkg.binary_package_name,
                               bin_pkg.binary_package_version,
                               bin_pkg.component_name, component))
            else:
                error("No results returned by getPublishedSources")
                sys.exit(1)

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        # Handle command line errors.
        #
        except CmdlineError as e:
            cmdline.error(e.msg, self.defaults)

        return

if __name__ == '__main__':
    app = CheckComponent()
    app.main()

# vi:set ts=4 sw=4 expandtab:

