#!/usr/bin/env python
#

from sys                                import argv
from getopt                             import getopt, GetoptError
from ktl.utils                          import stdo, eout
from ktl.std_app                        import StdApp
from ktl.git                            import Git, GitError
from ktl.debian                         import Debian, DebianError
from ktl.kernel                         import map_kernel_version_to_ubuntu_release
from lpltk.service                      import LaunchpadService, LaunchpadServiceError
from lazr.restfulclient.errors          import HTTPError

# CmdlineError
#
# The type of exception that will be raised by Cmdline.process() if there
# are command line processing errors.
#
class CmdlineError(Exception):
    # __init__
    #
    def __init__(self, error):
        self.msg = error

# Cmdline
#
# Do all the command line processing.
#
class Cmdline:
    # __init__
    #
    def __init__(self):
        self.cfg = {}

    # error
    #
    def error(self, e, defaults):
        if e != '': print e
        self.usage(defaults)

    # usage
    #
    # Prints out the help text which explains the command line options.
    #
    def usage(self, defaults):
        stdo("    Usage:                                                                                   \n")
        stdo("        %s [options]                                                                         \n" % self.cfg['app_name'])
        stdo("                                                                                             \n")
        stdo("    Options:                                                                                 \n")
        stdo("        --help           Prints this text.                                                   \n")
        stdo("                                                                                             \n")
        stdo("        --staging        Use the staging LP server to create the bug. This is just for       \n")
        stdo("                         testing and will go away when the database is reset.                \n")
        stdo("                                                                                             \n")
        stdo("        -version         What is the version number of the stable release. This is used      \n")
        stdo("                         for the bug title, to determine the series, etcl.                   \n")
        stdo("                                                                                             \n")
        stdo("    Examples:                                                                                \n")
        stdo("        %s --staging                                                                         \n" % self.cfg['app_name'])

    # process
    #
    # As you can probably tell from the name, this method is responsible
    # for calling the getopt function to process the command line. All
    # parameters are processed into class variables for use by other
    # methods.
    #
    def process(self, argv, defaults):
        self.cfg['app_name'] = argv[0]
        result = True
        try:
            optsShort = ''
            optsLong  = ['help', 'staging', 'version=']
            opts, args = getopt(argv[1:], optsShort, optsLong)

            for opt, val in opts:
                if (opt == '--help'):
                    raise CmdlineError('')

                elif (opt == '--staging'):
                    self.cfg['staging'] = True

                elif (opt == '--version'):
                    self.cfg['version'] = val

        except GetoptError, error:
            print(error, defaults)
            raise CmdlineError('')

        return self.cfg

    # verify_options
    #
    def verify_options(self, cfg):
        if 'version' not in self.cfg:
            raise CmdlineError('The version command line parameter is required.')
        return


# AppError
#
# A general exception that can be raised when an error is encountered in the app.
#
class AppError(Exception):
    # __init__
    #
    def __init__(self, error=''):
        self.msg = error

# CreateTrackingBug
#
class CreateTrackingBug(StdApp):
    # __init__
    #
    def __init__(self):
        StdApp.__init__(self)
        self.defaults = {}

    # initialize
    #
    def initialize(self):
        if 'staging' in self.cfg:
            self.defaults['launchpad_services_root'] = 'staging'
        try:
            self.lp = LaunchpadService(self.defaults)
        except LaunchpadServiceError, e:
            print(e.msg)
            raise

    # main
    #
    def main(self):
        cmdline = Cmdline()
        try:
            self.merge_config_options(self.defaults, cmdline.process(argv, self.defaults))
            cmdline.verify_options(self.cfg)
            self.initialize()

            #-------------------------------------------------------------------------------------
            # B U G   W O R K
            print("version: %s" % self.cfg['version'])
            m = Debian.version_rc.match(self.cfg['version'])
            if m == None:
                raise AppError("The version (%s) is not a recognized version string." % (self.cfg['version']))
            version = m.group(1)
            abi     = m.group(2)

            vur = map_kernel_version_to_ubuntu_release
            series = vur[m.group(1)]['name']

            # Title:
            title = "%s update to %s stable release" % (series.title(), self.cfg['version'])

            # Description
            description = """
    SRU Justification

    Impact:
       The upstream process for stable tree updates is quite similar
       in scope to the Ubuntu SRU process, e.g., each patch has to
       demonstrably fix a bug, and each patch is vetted by upstream
       by originating either directly from Linus' tree or in a minimally
       backported form of that patch. The %s.%s upstream stable
       patch set is now available. It should be included in the Ubuntu
       kernel as well.

       git://git.kernel.org/

    TEST CASE: TBD

       The following patches are in the %s.%s stable release:

            """ % (version, abi, version, abi)

            bug = self.lp.create_bug(project='ubuntu', package='linux', title=title, description=description)

            # Tags:
            #    kernel-stable-tracking-bug
            #
            bug.tags.append('kernel-stable-tracking-bug')

            # Teams / individuals to be automatically subscribed to the tracking bugs
            #   Hardware Certification Team     "hardware-certification"
            #   SRU Verification                "sru-verification"
            #   Ubuntu Stable Release           "ubuntu-sru"
            #
            teams = ["sru-verification", "ubuntu-sru"]
            for team in teams:
                lp_team = self.lp.launchpad.people[team]
                bug.lpbug.subscribe(person=lp_team)

            # For the given version, figure out the series and nominate that series.
            #
            lp = self.lp.launchpad
            ubuntu = lp.distributions["ubuntu"]
            sc = ubuntu.series_collection
            for s in sc:
                if s.name == series:
                    nomination = bug.lpbug.addNomination(target=s)
                    if nomination.canApprove():
                        nomination.approve()

            if 'staging' in self.cfg:
                print("https://bugs.staging.launchpad.net/bugs/%s" % (bug.id))
            else:
                print("https://bugs.launchpad.net/bugs/%s" % (bug.id))

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        # Handle ommand line errors.
        #
        except CmdlineError as e:
            cmdline.error(e.msg, self.defaults)

        except GitError as e:
            eout(e.msg[0])

        except DebianError as e:
            eout(e.msg)

        return

if __name__ == '__main__':
    app = CreateTrackingBug()
    app.main()

# vi:set ts=4 sw=4 expandtab:

