#!/bin/bash
for ver in 24 32 35 38
do
wget https://launchpad.net/ubuntu/+archive/primary/+files/linux_2.6.$ver.orig.tar.gz
done

# Link any special ones here, for ec2 or whatever
#ln -s linux_2.6.35.orig.tar.gz linux-ti-omap4_2.6.35.orig.tar.gz


