#!/usr/bin/env python
#

from sys                                import argv
from getopt                             import getopt, GetoptError
from ktl.utils                          import stdo, run_command
from ktl.std_app                        import StdApp
import json
import re


filename = argv[1]

f = open(filename, 'r')
versions = json.load(f)
f.close() 


for series, sinfo in versions.items():
    series_printed = False
    for package, pinfo in versions[series].items():
        ppa_version = versions[series][package]['PPA']
        proposed_version =  versions[series][package]['Proposed']
        updates_version =  versions[series][package]['Updates']
        security_version =  versions[series][package]['Security']

        pkg = package.ljust(30)
        pv = ppa_version.ljust(20)
        if ppa_version == '':
            continue
        if ppa_version == proposed_version:
            if not series_printed:
                print '=====', series, '====='
                series_printed = True
            print pkg, pv, 'Also in -proposed'
            continue
        if ppa_version == updates_version:
            if not series_printed:
                print '=====', series, '====='
                series_printed = True
            print pkg, pv, 'Also in -updates'
            continue
        if ppa_version == security_version:
            if not series_printed:
                print '=====', series, '====='
                series_printed = True
            print pkg, pv, 'Also in -security'

