#!/usr/bin/env python
#

from sys                                import argv
from getopt                             import getopt, GetoptError
from ktl.utils                          import stdo, run_command
from ktl.std_app                        import StdApp
from ktl.kernel                         import kernel_package_names, map_kernel_version_to_ubuntu_release
from launchpadlib.launchpad             import Launchpad
from os.path                            import basename
from urllib                             import urlopen
import json
import re

# CmdlineError
#
# The type of exception that will be raised by Cmdline.process() if there
# are command line processing errors.
#
class CmdlineError(Exception):
    # __init__
    #
    def __init__(self, error):
        self.msg = error

# Cmdline
#
# Do all the command line processing.
#
class Cmdline:
    # __init__
    #
    def __init__(self):
        self.cfg = {}

    # error
    #
    def error(self, e, defaults):
        if e != '': print e
        self.usage(defaults)

    # usage
    #
    # Prints out the help text which explains the command line options.
    #
    def usage(self, defaults):
        stdo("    Usage:                                                                                   \n")
        stdo("        %s [--verbose] [--config=<cfg file>] [--debug=<dbg options>]  outfile    \n" % self.cfg['app_name'])
        stdo("                                                                                             \n")
        stdo("    Fetch package information from the kernel team PPA and put it into a json file           \n")
        stdo("                                                                                             \n")
        stdo("    Options:                                                                                 \n")
        stdo("        --help           Prints this text.                                                   \n")
        stdo("                                                                                             \n")
        stdo("        --verbose        Give some feedback of what is happening while the script is         \n")
        stdo("                         running.                                                            \n")
        stdo("                                                                                             \n")
        stdo("        --config=<cfg file>                                                                  \n")
        stdo("                         The full path to the configuration file to use instead of           \n")
        stdo("                         the default location.                                               \n")
        stdo("                                                                                             \n")
        stdo("        --debug=<debug options>                                                              \n")
        stdo("                         Performs additional output related to the option enabled and        \n")
        stdo("                         the application defined support for the option.                     \n")
        stdo("                                                                                             \n")
        stdo("    Examples:                                                                                \n")
        stdo("        %s --verbose                                                                         \n" % self.cfg['app_name'])

    # process
    #
    # As you can probably tell from the name, this method is responsible
    # for calling the getopt function to process the command line. All
    # parameters are processed into class variables for use by other
    # methods.
    #
    def process(self, argv, defaults):
        self.cfg['app_name'] = argv[0]
        result = True
        try:
            optsShort = ''
            optsLong  = ['help', 'verbose', 'config=', 'debug=']
            opts, args = getopt(argv[1:], optsShort, optsLong)
            if len(args) != 1:
                raise CmdlineError('You must supply an output file name\n\n')
                
            self.cfg['args'] = args

            for opt, val in opts:
                if (opt == '--help'):
                    raise CmdlineError('')

                elif (opt == '--verbose'):
                    self.cfg['verbose'] = True

                elif opt in ('--config'):
                    self.cfg['configuration_file'] = val

                elif opt in ('--debug'):
                    self.cfg['debug'] = val.split(',')

        except GetoptError, error:
            print(error, defaults)
            raise CmdlineError('')

        return self.cfg

    # verify_options
    #
    def verify_options(self, cfg):
        return

def contains(theString, theQueryValue):
  return theString.find(theQueryValue) > -1

# 
#
class rMadison(StdApp):
    # __init__
    #
    def __init__(self):
        StdApp.__init__(self)
        self.defaults = {}

    # main
    #
    def main(self):
        cmdline = Cmdline()
        try:
            self.merge_config_options(self.defaults, cmdline.process(argv, self.defaults))
            cmdline.verify_options(self.cfg)

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        # Handle command line errors.
        #
        except CmdlineError as e:
            cmdline.error(e.msg, self.defaults)
            return

        # Do the work
        #
        jf = open(self.cfg['args'][0], 'w+')

        resultinfo = {}
        for package in kernel_package_names:
            packageinfo = {}
            print 'Fetching information for ', package
            cmdline = 'rmadison -asource ' + package
            status, result = run_command(cmdline)
            if (status):
                print "ERROR: Error running command <", cmdline, ">"
            else:
                for line in result:
                    packagename, version, distpocket, package_type = line.split('|')
                    pktparts =  distpocket.strip().split('-')
                    if len(pktparts) == 1:
                        # we don't care about the original version
                        continue
                    else:
                        pocket =  distpocket.strip().split('-')[-1]
                    rm = re.match('[0-9]\.[0-9]\.[0-9][0-9]', version.strip())
                    baseversion = rm.group(0)
                    distribution = map_kernel_version_to_ubuntu_release[baseversion]['name']

                    packageinfo['name'] = packagename.strip()
                    packageinfo['version'] = version.strip()
                    packageinfo['pocket'] = pocket.strip()
                    packageinfo['distribution'] = distribution.strip()
                    resultkey = package.strip() + '-' + version.strip()
                    resultinfo[resultkey] = packageinfo
                    
        jf.write(json.dumps(resultinfo, sort_keys=True, indent=4))

        return

if __name__ == '__main__':
#    app = PPAinfo('sconklin')
    app = rMadison()
    app.main()

# vi:set ts=4 sw=4 expandtab:

