#!/bin/sh -x

set +e

# Generate several charts from bonnie data

./merge_benchmark_data --job-name=bonnie-test --only-metrics="seqin_perblk_ksec{perf},seqout_perblk_ksec{perf}" sample-bench-data/*.json > ./bonnie.json
./benchmark-report --title="Bonnie - Block In/Out" ./bonnie.json
mv index.html bonnieblk.html

./merge_benchmark_data --job-name=bonnie-test --only-metrics="seqin_perchr_ksec{perf},seqout_perchr_ksec{perf}" sample-bench-data/*.json > ./bonnie.json
./benchmark-report --title="Bonnie - Character In/Out" ./bonnie.json
mv index.html bonniechr.html

./merge_benchmark_data --job-name=bonnie-test --mute-metrics="size{perf}" sample-bench-data/*.json > ./bonnie.json
./benchmark-report --title="Bonnie - All" ./bonnie.json
mv index.html bonnie.html

# Generate the dbench chart

./merge_benchmark_data --job-name=dbench-test  --mute-metrics="procs{perf}" sample-bench-data/*.json > ./dbench.json
./benchmark-report --title="Dbench Benchmark" ./dbench.json
mv index.html dbench.html

scp dbench.html bonnieblk.html bonniechr.html bonnie.html ai4qr.com:ai4qr.com/foo/
