#!/bin/sh -x

set +e

# Generate several charts from bonnie data
JOBNAME=statler-bonnie
DATALOC=metrics

# Specify a baseline data file to normalize all data to that file
# The baseline file must contain all the metrics to be published. It can also contain additional ones, which will be ignored
#BASELINE="--baseline=statler-bonnie-baseline.json"

./merge_benchmark_data --job-name=$JOBNAME $BASELINE --chart-title="Block I/O" --only-metrics="seqin_perblk_ksec{perf},seqout_perblk_ksec{perf}" $DATALOC/*.json > ./block.json

./merge_benchmark_data --job-name=$JOBNAME $BASELINE --chart-title="Char I/O" --only-metrics="seqin_perchr_ksec{perf},seqout_perchr_ksec{perf}" $DATALOC/*.json > ./char.json

./benchmark-report --onepage --title="Quantal Bonnie Results" block.json char.json
#mv index.html $JOBNAME-bonnieblk.html
exit
./merge_benchmark_data --job-name=$JOBNAME $BASELINE --only-metrics="seqin_perchr_ksec{perf},seqout_perchr_ksec{perf}" $DATALOC/*.json > ./bonnie.json
./benchmark-report --title="Quantal Bonnie - Character In/Out" ./bonnie.json
mv index.html $JOBNAME-bonniechr.html

./merge_benchmark_data --job-name=$JOBNAME $BASELINE --mute-metrics="size{perf}" $DATALOC/*.json > ./bonnie.json
./benchmark-report --title="Quantal Bonnie - All" ./bonnie.json
mv index.html $JOBNAME-bonnie.html

scp $JOBNAME-bonnieblk.html $JOBNAME-bonniechr.html $JOBNAME-bonnie.html ai4qr.com:ai4qr.com/foo/

# Generate the dbench chart
#JOBNAME=statler-dbench
#DATALOC=for-lava
#
#./merge_benchmark_data --job-name=$JOBNAME  --mute-metrics="procs{perf}" $DATALOC/*.json > ./dbench.json
#./benchmark-report --title="Quantal Dbench Benchmark" ./dbench.json
#mv index.html dbench.html

#scp dbench.html ai4qr.com:ai4qr.com/foo/
