#!/bin/sh

set +e

#
# Do public Charts
#
echo "==============="
unset PRIVATE
export SYSNAME="statler"
export TITLENAME="Statler"
./chart-system
export SYSNAME="waldorf"
export TITLENAME="Waldorf"
./chart-system

#
# Do private Charts
#

echo "==============="
export PRIVATE=True
export SYSNAME="statler"
export TITLENAME="Statler"
./chart-system
export SYSNAME="waldorf"
export TITLENAME="Waldorf"
./chart-system

echo "==============="
#
# Eventually, trigger the rsync here
#

