#
# Makefile for the Marvell Gigabit Ethernet driver
#

ifdef CONFIG_MV_HAL_RULES_PATH
include $(TOPDIR)/include/config/auto.conf
include $(TOPDIR)/$(subst ",,$(CONFIG_MV_HAL_RULES_PATH))
endif

obj-$(CONFIG_MV_ETH_NFP) += mv_nfp_mgr.o

