#!/bin/bash
#
# Copyright (C) 2010 Canonical
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
FWTS="Firmware Test Suite"
OPTIONS="/tmp/options.$$"
DIALOG_CMD="/tmp/fwts.cmd.$$"

FWTS_DATE=`date +%d%m%Y`
FWTS_TIME=`date +%H%M`
WORK_DIR=/isodevice/fwts/$FWTS_DATE/$FWTS_TIME

#
#  Run a bunch of tests and monitor progress
#
do_test()
{
	
	num_tests=`fwts $1 --show-tests | wc -l`
	num_tests=$((num_tests - 1))
	if [ $num_tests -gt 0 ]; then
  		fwts --skip-test=s3,s4 $1 --show-progress-dialog | dialog --title "$2" --gauge "" 15 80 0
	fi
}

select_tests()
{
	declare -a tests
	x=0
#
#  Discover available tests
#
	fwts --batch --batch-experimental --show-tests | grep "^ " > $OPTIONS
	while read test text
	do
		((x++))
		tests[$x]=$test
		txt="${txt} ${x} \"${text}\" off"
	done < $OPTIONS
	rm $OPTIONS
#
# Construct and run dialog
#
	echo dialog --checklist '"Select from the list below the test(s) you want to run:"' 20 70 $x $txt > $DIALOG_CMD
	. $DIALOG_CMD 2> $OPTIONS
	rm $DIALOG_CMD
#
# Scan return selections and build fwts test scenarios
#
	x=0
	for i in `cat $OPTIONS`
	do
		((x++))
		i=${i#\"}
		i=${i%\"}
		run_tests="$run_tests ${tests[$i]}"
	done

	if [ $x -eq 0 ]; then
		run=0
	else
  		fwts $run_tests --show-progress-dialog | dialog --title "$2" --gauge "" 15 80 0
		run=1
	fi
}

cd /cdrom
mkdir -p $WORK_DIR >& /dev/null
if [ $? -ne 0 ]; then
	dialog --ok-label "Shutdown" --backtitle "$FWTS" --title "Error" --msgbox "Could not create directory fwts/$FWTS_DATE/$FWTS_TIME.\n          Press Enter to shutdown." 6 50 
	# shutdown -h now
	exit
else
  	dialog --backtitle "$FWTS" --title "Select Tests" --radiolist \
  	"This will run a suite of firmware tests that will check the BIOS and ACPI tables. It will also find issues that can cause Linux problems.\n\n\
The default below is to run just all the Batch Tests, but you can select more tests below if required.\n\nPlease Select Tests and press Enter to continue:" \
	20 70 4 \
	1 "All Batch Tests" on \
	2 "All Experimental Batch Tests" off \
	3 "Select Individual Tests" off \
	4 "Abort Testing" off \
2> $OPTIONS
	cd $WORK_DIR >& /dev/null

	run=0
#
#  See what needs running
#
  	for i in `cat $OPTIONS`
  	do
		case $i in
		'1')
  			do_test "--batch" 'Running Batch Tests'
			run=1
		;;
		'2')
			do_test "--batch-experimental" 'Running Experimental Batch Tests'
			run=1
		;;
		'3')
			select_tests
		;;
		'4')
			run=0
		;;
		esac
	done
	
#
# All done, get ready to shutdown
#
	if [ $run -eq 0 ]; then
	dialog  --backtitle "$FWTS" --title "No Tests Run!" --msgbox \
"   You did not select any tests to be run.\n
          Press Enter to shutdown." 7 50
	else
	dialog  --backtitle "$FWTS" --title "Information" --msgbox \
"The results can be found on the USB stick in the\n
the directory: /fwts/$FWTS_DATE/$FWTS_TIME/results.log\n\n
            Press Enter to shutdown" 9 55
	fi
  	shutdown -h now
fi

