#!/bin/sh

# Assume that this is the first time and we are running
# off of a flash drive.
#

# Need to create the mount point for the flash drives'
# secod partition which has the kernel-qa tree on it.
#
if [ ! -e "/ukt" ]; then
    sudo mkdir /ukt
    sudo chmod +rwx /ukt
fi

# Try to mount the second partition on the mount point.
# If we succeed, then create a link in current directory
# to the kernel-qa tree on the second partition.
#
if [ ! -e "/ukt/kernel-qa" ]; then
    sudo mount /dev/sdb2 /ukt
    if [ -e "/ukt/kernel-qa" ]; then
        ln -s /ukt/kernel-qa ./kernel-qa-tests
        if [ ! -e $HOME/results ]; then
            ln -s /ukt/results $HOME/results
        fi
    else
        if [ -d "kernel-qa" ]; then
            ln -s kernel-qa ./kernel-qa-tests
        fi
        if [ ! -d "results" ]; then
            mkdir results
        fi
    fi
fi

sleep 3

gnome-terminal -e ./kernel-qa-tests/tests_starter
