#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <experimental> <config directory>" 1>&2
	exit 1
fi
experimental="$1"
configs="$2"

all=`ls -1 "$configs"`
#cmp=''
#for i in $all
#do
#	cmp="$cmp `echo "$i" | sed -e 's/config\.flavour\.//'`"
#done
#echo "cmp<$cmp>"

rm -rf tmp
mkdir -p tmp

level='===='

function rebuild() {
	local what="$1"
	local out
	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		egrep -h "$what" "$configs/$i" | sort >"tmp/$out"
	done
}
function config-cmp() {
	(cd tmp; "$here/config-compare" --experimental "../$experimental" *)
}

what='_FS[ =]'
rebuild "$what"

echo ""
echo "$level Filesystems $level"
config-cmp $cmp
echo ""

##what='CONFIG_(LSM_MMAP_MIN_ADDR|DEFAULT_MMAP_MIN_ADDR|APPARMOR|SELINUX|TOMOYO|COMPAT_BRK|DEVKMEM|SYN_COOKIES|SECURITY|SECCOMP|COMPAT_VDSO|DEBUG_RODATA|STRICT_DEVMEM|SECURITY_FILE_CAPABILITIES|SECURITY_SMACK|CC_STACKPROTECTOR)[ =]'
##rebuild "$what"
##
##echo ""
##echo "$level Security $level"
##config-cmp $cmp
##echo ""

what='CONFIG_(PCI|USB|BT|SCSI|APM|ACPI|NET|NETFILTER|ATA|INPUT|HID)[ =]'
rebuild "$what"

echo ""
echo "$level Subsystems $level"
config-cmp $cmp
echo ""

what="(CONFIG_NET_9P|CONFIG_ATM|CONFIG_AX25|CONFIG_BRIDGE|CONFIG_CAIF|CONFIG_CAN|CONFIG_DCB|CONFIG_DECNET|CONFIG_DNS_RESOLVER|CONFIG_NET_DSA|CONFIG_ECONET|CONFIG_NET_ETHERNET|CONFIG_IEEE802154|CONFIG_IPV6|CONFIG_IPX|CONFIG_IRDA|CONFIG_NET_KEY|CONFIG_L2TP|CONFIG_LAPB|CONFIG_LLC|CONFIG_MAC80211|CONFIG_NETFILTER|CONFIG_NETLABEL|CONFIG_NETROM|CONFIG_PACKET|CONFIG_PHONET|CONFIG_RDS|CONFIG_RFKILL|CONFIG_ROSE|CONFIG_NET_SCHED|CONFIG_SUNRPC|CONFIG_TIPC|CONFIG_UNIX|CONFIG_WIMAX|CONFIG_WIRELESS|CONFIG_X25|CONFIG_XFRM)[ =]"
rebuild "$what"

echo ""
echo "$level Network Protocols $level"
config-cmp $cmp
echo ""

what='CONFIG_(ATA|SATA|PATA)_'
rebuild "$what"

echo ""
echo "$level {,S,P}ATA Drivers $level"
config-cmp $cmp
echo ""

what='CONFIG_INPUT_'
rebuild "$what"

echo ""
echo "$level Input Drivers $level"
config-cmp $cmp
echo ""

what='CONFIG_HID_'
rebuild "$what"

echo ""
echo "$level HID Drivers $level"
config-cmp $cmp
echo ""
