#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

which="$1"
from_info="$2"
info="$3"
configs="$4"

. "$here/lib-output"

output_info "$info"
output_configs "$configs"

from="/tmp/devel-config-from.$$"
to="/tmp/devel-config-to.$$"

awk '/flag<'"$which"'>/ { print $1 }' <"$from_info" >"$from"
awk '/flag<'"$which"'>/ { print $1 }' <"$info" >"$to"

rm -rf tmp
mkdir -p tmp

pattern=`
	diff -u "$from" "$to" | \
		grep ^-C | \
		sort -u | \
		sed -e 's/^-//' | \
		while read C
		do
			egrep "^$C " "$info"
		done | \
		while read conf maybe default expected options
		do
			echo -n "|$conf"
		done | \
		sed -e 's/^|/(/' -e 's/$/)[ =]/'
`
if [ "$pattern" = "" ]; then
	pattern="nothing-to-see-here"
fi
rebuild "$pattern"

diff -u "$from" "$to" | \
	grep ^-C | \
	sort -u | \
	sed -e 's/^-//' >tmp/.required

output_header "No longer $which"
config-cmp --colour --required .required
output_footer

rm -f "$from" "$to"
