#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <info> <config directory>" 1>&2
	exit 1
fi
info="$1"
configs="$2"

all=`ls -1 "$configs"`
#cmp=''
#for i in $all
#do
#	cmp="$cmp `echo "$i" | sed -e 's/config\.flavour\.//'`"
#done
#echo "cmp<$cmp>"

rm -rf tmp
mkdir -p tmp

level='===='

function rebuild() {
	local what="$1"
	local not="$2"
	local out
	rm -f "tmp/*"

	[ "$not" = "" ] && not="^NOT_VALID"

	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		egrep -h "$what" "$configs/$i" | egrep -h -v "$not" | \
			sort >"tmp/$out"
	done
}
function config-cmp() {
	(cd tmp; "$here/config-compare" --info "../$info" $@ *)
}
function config-cmp-nopolicy() {
	(cd tmp; "$here/config-compare" --no-policy --info "../$info" *)
}
function config-cmp-interesting() {
	(cd tmp; "$here/config-compare" --info "../$info" *) | grep -v '||  ||$'
	(cd tmp; "$here/config-compare" --info "../$info" *) | grep '||  ||$'
}

function colourise() {
	awk '
		/BUILD FAILURE/ { gsub("\\|\\| ", "||<#baffc8> "); }
		/Inconsistent/ { gsub("\\|\\| ", "||<#ffbac8> "); }
		{print }
	'
}
function colourise_inverse() {
	awk '/\|\|  *\('"'''\(EXPERIMENTAL|STAGING|DEBUG\)'''"'\)* \|\|/ { gsub("\\|\\| ", "||<#ffbac8> ")} { print }'
}

list_core() {
	local variant="$1"
	local flags="$2"
	local title="$3"
	local what="$4"
	local not="$5"

	rebuild "$what" "$not"
	echo ""
	echo "$level $title $level"
	config-cmp$variant $flags $cmp | colourise
	echo ""
}
list_interesting() {
	list_core "-interesting" "" "$@"
}
list_sort() {
	list_core "" "--sort" "$@"
}
list() {
	list_core "" "" "$@"
}

list_interesting "Filesystems" 'FS[ =]' "CONFIG_.*(_DEBUG_FS|_PROC_FS|_DEBUGFS|_PROCFS|_SYSFS|_PARTITION_.*)[ =]"

#list 'Security' 'CONFIG_(LSM_MMAP_MIN_ADDR|DEFAULT_MMAP_MIN_ADDR|APPARMOR|SELINUX|TOMOYO|COMPAT_BRK|DEVKMEM|SYN_COOKIES|SECURITY|SECCOMP|COMPAT_VDSO|DEBUG_RODATA|STRICT_DEVMEM|SECURITY_FILE_CAPABILITIES|SECURITY_SMACK|CC_STACKPROTECTOR)[ =]' ''

list_interesting 'Subsystems' 'CONFIG_(PCI|USB|BT|SCSI|APM|ACPI|NET|NETFILTER|ATA|INPUT|HID)[ =]' ''

list_interesting 'Network Protocols' '(CONFIG_NET_9P|CONFIG_ATM|CONFIG_AX25|CONFIG_BRIDGE|CONFIG_CAIF|CONFIG_CAN|CONFIG_DCB|CONFIG_DECNET|CONFIG_DNS_RESOLVER|CONFIG_NET_DSA|CONFIG_ECONET|CONFIG_NET_ETHERNET|CONFIG_IEEE802154|CONFIG_IPV6|CONFIG_IPX|CONFIG_IRDA|CONFIG_NET_KEY|CONFIG_L2TP|CONFIG_LAPB|CONFIG_LLC|CONFIG_MAC80211|CONFIG_NETFILTER|CONFIG_NETLABEL|CONFIG_NETROM|CONFIG_PACKET|CONFIG_PHONET|CONFIG_RDS|CONFIG_RFKILL|CONFIG_ROSE|CONFIG_NET_SCHED|CONFIG_SUNRPC|CONFIG_TIPC|CONFIG_UNIX|CONFIG_WIMAX|CONFIG_WIRELESS|CONFIG_X25|CONFIG_XFRM)[ =]' ''

list_interesting 'INET/INET6 Networking' 'CONFIG_INET6?_' ''

list_interesting '{,S,P}ATA Drivers' 'CONFIG_(ATA|SATA|PATA)_' ''

list_interesting 'Input Drivers' 'CONFIG_INPUT_' 'CONFIG_INPUT_(KXTJ9_POLLED_MODE)[ =]'

list_interesting 'HID Drivers' 'CONFIG_HID_' ''

list_interesting 'Sensor Drivers' 'CONFIG_SENSORS_' ''

list_interesting 'Crypto/CRC' 'CONFIG_(CRYPTO_|CRC_|CRC[0-9]+)' ''

list_interesting 'Netfilter Match/Targets' 'CONFIG_NETFILTER_XT_' ''

list_interesting 'Block and Character devices' 'CONFIG_(BLK|CHR)_DEV_' ''

list_interesting 'PHY support' 'CONFIG_(.*_PHY|PHYLIB)[_ =]' ''

list_interesting 'Device Mapper' 'CONFIG_DM[_ =]' ''

list_interesting "RTC Drivers" "CONFIG_RTC_DRV_" ""

list_interesting "Keyboard/Mouse Drivers" "CONFIG_(KEYBOARD|MOUSE)_" ""

list_interesting "USB support" "CONFIG_USB_" ""

list_interesting "GPIO support" "CONFIG_GPIO_" ""

list_interesting "I2C support" "CONFIG_I2C_" ""

function what_flag()
{
	typeset flag="$1"

	what=`awk '/flag<'"$flag"'>/ { print $1 }' <"$info" |
		tr '\n' '|' | sed -e 's/^/(/' -e 's/|$/)[ =]/'`
}

what_flag 'DANGEROUS'
list_interesting 'DANGEROUS Options' "$what" ''

what_flag 'DEPRECATED'
list_interesting 'DEPRECATED Options' "$what" ''

what_flag 'BUILD FAILURE'
list_interesting 'BUILD FAILURES' "$what" ''

rebuild ""
awk '($2 ~ /[Mm]/) { print $1 "=m" }' <"$info" >"tmp/000-MODULES"
what=`config-cmp-nopolicy $cmp | tee APW | \
	awk '($4 ~ /m/ && /'"'''Inconsistent'''"'/) { print $2 }' | tee APW2 | \
		tr '\n' '|' | sed -e 's/^/(/' -e 's/|$/)[ =]/'`
rm tmp/000-MODULES
list_sort 'Non-modular modules' "$what" ''
