#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

from="$1"
to="$2"
experimental="$3"
info="$4"
configs="$5"

. "$here/lib-output"

output_info "$info"
output_configs "$configs"

rm -rf tmp
mkdir -p tmp

pattern=`
	diff -u "$from" "$to" | \
		grep ^+C | \
		sort -u | \
		sed -e 's/^+//' | \
		while read conf maybe default expected options
		do
			echo -n "|$conf"
		done | \
		sed -e 's/^|/(/' -e 's/$/)[ =]/'
`
rebuild "$pattern"

output_header "New Options"
config-cmp --colour
output_footer
