#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

which="$1"
from_info="$2"
to_info="$3"
configs="$4"

from="/tmp/devel-config-from.$$"
to="/tmp/devel-config-to.$$"

awk '/flag<'"$which"'>/ { print $1 }' <"$from_info" >"$from"
awk '/flag<'"$which"'>/ { print $1 }' <"$to_info" >"$to"

all=`ls -1 "$configs"`
#cmp=''
#for i in $all
#do
#	cmp="$cmp `echo "$i" | sed -e 's/config\.flavour\.//'`"
#done
#echo "cmp<$cmp>"

rm -rf tmp
mkdir -p tmp

level='===='

function rebuild() {
	local what="$1"
	local out
	rm -f tmp/.required
	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		egrep -h "$what" "$configs/$i" | sort >"tmp/$out"
	done
}
function config-cmp() {
	opts=''
	if [ -f tmp/.required ]; then
		opts="$opts --required .required"
	fi
	call=''
	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		call="$call $out"
	done
	(cd tmp; "$here/config-compare" $opts --info "../$to_info" $call "$@")
}
function colourise() {
	awk '
		/BUILD FAILURE/ { gsub("\\|\\| ", "||<#baffc8> "); }
		/Inconsistent/ { gsub("\\|\\| ", "||<#ffbac8> "); }
		{print }
	'
}

pattern=`
	diff -u "$from" "$to" | \
		grep ^-C | \
		sort -u | \
		sed -e 's/^-//' | \
		while read C
		do
			egrep "^$C " "$to_info"
		done | \
		while read conf maybe default expected options
		do
			echo -n "|$conf"
		done | \
		sed -e 's/^|/(/' -e 's/$/)[ =]/'
`
if [ "$pattern" = "" ]; then
	pattern="nothing-to-see-here"
fi
rebuild "$pattern"

diff -u "$from" "$to" | \
	grep ^-C | \
	sort -u | \
	sed -e 's/^-//' >tmp/.required


echo "$level No longer $which $level"
config-cmp | colourise
echo ""

rm -f "$from" "$to"
