#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

which="$1"
from="$2"
to="$3"
defaults="$4"
configs="$5"

all=`ls -1 "$configs"`
#cmp=''
#for i in $all
#do
#	cmp="$cmp `echo "$i" | sed -e 's/config\.flavour\.//'`"
#done
#echo "cmp<$cmp>"

rm -rf tmp
mkdir -p tmp

level='===='

function rebuild() {
	local what="$1"
	local out
	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		egrep -h "$what" "$configs/$i" | sort >"tmp/$out"
	done
}
function config-cmp() {
	call=""
	for i in $all
	do
		out=`echo "$i" | sed -e 's/config\.flavour\.//'`
		call="$call $out"
	done
	(cd tmp; "$here/config-compare" $call "$@")
}


pattern=`
	diff -u "$from" "$to" | \
		grep ^-C | \
		sort -u | \
		sed -e 's/^-//' | \
		while read C
		do
			egrep "^$C " "$defaults"
		done | \
		while read conf default expected
		do
			echo -n "|$conf"
		done | \
		sed -e 's/^|/(/' -e 's/$/)[ =]/'
`
if [ "$pattern" = "" ]; then
	pattern="nothing-to-see-here"
fi
rebuild "$pattern"

diff -u "$from" "$to" | \
	grep ^-C | \
	sort -u | \
	sed -e 's/^-//' | \
	while read C
	do
		egrep "^$C " "$defaults" || echo "$C - -"
	done | \
	while read conf default expected
	do
		case "$expected" in
		n)	echo "# $conf is not set" ;;
		*)	echo "$conf=$expected" ;;
		esac
	done >"tmp/Policy"

echo "$level No longer $which $level"
config-cmp Policy
echo ""
