#!/bin/bash
#
# devel-info-dump <directory>
#
here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <OVERRIDES> <directory>" 1>&2
	exit 1
fi
over="$1"
dir="$2"

cd "$dir" || {
	echo "$0: $dir: directory not found" 1>&2
	exit 1
}

"$here/devel-config-defaults" >"CONFIGS-dump"

"$here/devel-config-tag" \
	"CONFIGS-dump" "$over" >"CONFIGS-info"
awk '{ print $1 " " $2 " " $3 }' <"CONFIGS-info" >"CONFIGS-defaults"
