#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

format="$1"
from="$2"
to="$3"
experimental="$4"
info="$5"
configs="$6"

. "$here/lib-output"

output_format "$format"
output_info "$info"
output_configs "$configs"

rm -rf tmp
mkdir -p tmp

pattern=`
	diff -u "$from" "$to" | \
		grep ^+C | \
		sort -u | \
		sed -e 's/^+//' | \
		while read conf maybe default expected options
		do
			echo -n "|$conf"
		done | \
		sed -e 's/^|/(/' -e 's/$/)[ =]/'
`
rebuild "$pattern"

output_header "New Options"
config-cmp --colour
output_footer
