#! /bin/bash

. debian/debian.env

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <option>" 1>&2
	exit 1
fi
depends="$1"

# Ensure the configs are clean in tree.
git checkout -f >&2

over="$DEBIAN/config/OVERRIDES"

fakeroot debian/rules clean >/dev/null 2>&1

# Remove all options which depend on this option
echo "# $depends is not set" >"$over"
fakeroot debian/rules defaultconfigs defaultportsconfigs >/dev/null 2>&1

# Enable option and rebuild the configs, all options which are interesting
# and depend on it will appear as NEW.
echo "$depends=y" >"$over"
fakeroot debian/rules defaultconfigs defaultportsconfigs 2>&1 | \
perl -e '
	while (<>) {
		while ($_ =~ /\(([^\)]*)\) \[([^\]]*)\]\s+\(NEW\)/g) {
			($option, $default) = ($1, $2);
			next if ($option eq "");

			#$value = "n";
			#$value = "y" if ($default =~ /[yY]/);
			#$value = "m" if ($default =~ /[mM]/);

			$option = "CONFIG_$option";

			print "$option\n";
		}
	}
' | sort -u

# Ensure the configs are clean in tree once more.
git checkout -f >&2
rm -f "$over"
