#! /bin/bash

. debian/debian.env

# Ensure we get the configuration dump.
sed -ie 's@//zconfdump@zconfdump@' scripts/kconfig/conf.c || exit 1

fakeroot debian/rules dumpconfigs dumpportsconfigs 2>&1

sed -ie 's@zconfdump@//zconfdump@' scripts/kconfig/conf.c || exit 1
