# Dove Machine Support
snd-soc-dovedb-objs := dove_db.o

obj-$(CONFIG_SND_DOVE_SOC_DB) += snd-soc-dovedb.o

obj-$(CONFIG_SND_DOVE_SOC_MRVL_AUDIO) 	+= ../../../arch/arm/plat-orion/mv_hal_drivers/mv_drivers_lsp/mv_audio_soc/
