#!/bin/bash

LF=../cherry-pick.log

if [ "$1" = "-s" ]
then
	SOB="$1"
	shift
fi

CF=$1
if [ -z "${CF}" ] || [ ! -f ${CF} ]
then
	echo You must provide a list of commits to cherry pick.
	exit 1
fi

cat ${CF} | sed '/^#/d' | while read c j
do
	if ! git cherry-pick ${SOB} $c > ${LF}
	then
		if ! grep "nothing to commit" ${LF} > /dev/null
		then
			echo Cherry pick failed on "$c $j"
			exit 1
		fi
	fi
	cat ${LF}
done

