#!/bin/bash

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <patch file>" 1>&2
	echo
	echo "Open a patch file and all the files which are patched in the editor"
	exit 1
fi

PATCH=$1
if [ -z "${PATCH}" ] || [ ! -f ${PATCH} ]
then
	echo You must provide the name of a patch.
	exit 1
fi

FL=`lsdiff $PATCH | sed 's/^a\///' | tr '\n' ' '`

$EDITOR $PATCH $FL
