#!/bin/bash

TF="$(mktemp)"

for COMMIT in `git rev-list master..master-next`
do
  git log -1 $COMMIT > $TF
  if ! grep "BugLink" ${TF} > /dev/null
  then
      echo No Buglink in `git log -1 --oneline $COMMIT`
  fi
done

rm -f $TF