#! /bin/bash

if [ "$#" -lt 1 ]; then
	echo "Usage: maint-based-on <branch> ..." 1>&2
fi

for br in "$@"
do
	git log --pretty=one "$br" | \
	awk -v br="$br" '
		/Ubuntu-2\.6\./ {
			if (match($0, /UBUNTU: (Ubuntu-2\.6\.[0-9][0-9]*-([0-9][0-9]*)[^ ]*)/, a)) {
				#print a[1] " " a[0]

				if (a[2]+0 < 100 && a[2]+0 != 0) {
					print br " " $1 " " a[1]
					exit
				}
			}
		}
	'
done | \
while read branch sha1 tag
do
	tag_sha1=`git log --pretty=format:%H "$tag^..$tag" 2>/dev/null`
	if [ "$tag_sha1" = "" ]; then
		flag="?"
	elif [ "$tag_sha1" = "$sha1" ]; then
		flag=""
	else
		flag="+"
	fi
	printf "%-20.20s %s%s\n" "$branch" "$tag" "$flag"
done
