#!/bin/bash
export BROWSER="firefox"
export OPENURLS=false
CMD="$(basename $0)"
CHANGELOG="$(debian/rules printdebian 2>/dev/null || echo debian)/changelog"

function PrintUsage()
{
	cat <<-EOD
	Usage: $CMD [--openurls]
	EOD
}

while [ $# -gt 0 ]; do
	case $1 in
		--openurls)
			OPENURLS=true
			;;
		--help|-h)
			PrintUsage
			exit
			;;
	esac
	shift
done

if [ ! -f $CHANGELOG ]; then
	echo "$CHANGELOG, where art though?" >&2
	exit 1
fi

cat $CHANGELOG | awk '
	function CheckBug() {
		if (last_entry != "" && last_bug == 0) {
			print "EE: \"" last_entry "\" needs bug!"
			err++
		}
		last_entry = ""
		last_bug = 0
	}
	BEGIN{
		last_entry = ""
		url = "https://bugs.launchpad.net/ubuntu/+source/linux/+bug/"
	}
	FNR == 1 && /UNRELEASED/{
		print "EE: No release series and pocket!"
		err++
	}
	/urgency=low/ && FNR > 1{
		exit
	}
	/[ \t]+\*/{
		CheckBug()
		sub(/[ \t]+\* /, "")
		last_entry = $0
	}
	/- LP: /{
		sub(/.*- LP:[ \t]+/, "")
		split($0, N, ", ")
		for (i in N) {
			sub(/#/, "", N[i])
			bugs[N[i]] = FNR
			last_bug = N[i]
		}
	}
	END{
		urls = ""
		for (i in bugs) {
			print url i
			urls = urls " " url i
		}

		if (urls != "" && ENVIRON["OPENURLS"] == "true")
			system(ENVIRON["BROWSER"] urls)

		if (err) {
			print "There were " err " error(s)"
			exit 1
		}
	}
'

