#!/bin/bash

#
# Example: $0 maverick
#

. `pwd`/scripts/chroot-defs.conf

RELEASE=$1

[ -z "${RELEASE}" ] && exit 1

let index=0

for i in "${releases[@]}"
do
	if [ "$i" = "$RELEASE" ]
	then
		for j in ${arches[${index}]}
		do
			./remove_chroot ${RELEASE} $j
		done
	fi
	let index=${index}+1
done

