#!/bin/bash
#
# Unmount all schroot mounts
#
mount|grep schroot|while read m on f j; do sudo fuser -k "$f";sudo umount $f;done
mount|grep schroot|while read m on f j; do sudo fuser -k "$f";sudo umount $f;done
