#!/bin/bash
#
# Command line
#
VERBOSE=false
STATUSFILE="./build-status"
while [ $# -gt 0 ]; do
	case $1 in
		-v|--verbose)
			VERBOSE=true
			;;
		-*|--*)
			echo "Unknown option $1" >&2
			exit 1
			;;
		*)
			if [ "$DIR" = "" ]; then
				DIR="$1"
			else
				echo "Too many arguments" >&2
				exit 1
			fi
			;;
	esac
	shift
done

if [ ! -f $STATUSFILE ]; then
	echo "idle"
	exit 0
fi

. $STATUSFILE

if [ "$STATE" = "" ]; then
	echo "idle"
	exit 0
fi

case "$STATE" in
	failed)
		echo "idle(last build failed)"
		exit 0
		;;
	building)
		case "$BUILDTARGET" in
			kernel)
				CMD="run-kernel-status"
				DIR="ubuntu-2.6"
				;;
			lum)
				CMD="run-lum-status"
				DIR="ubuntu-2.6-lum"
				;;
			*)
				echo "building $BUILDTARGET"
				exit 0
				;;
		esac
		if ! $VERBOSE; then
			echo "building $BUILDTARGET"
			exit 0
		fi
		;;
	*)
		echo "$STATE"
		exit 0
		;;
esac

. $(dirname $0)/$CMD

