#!/bin/bash

#
# This script is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

cd `dirname $0`

#
# Change the ucode file name so that the updated firmware files don't clash.
#
sed -i 's/#define.*IWL3945_FW_PRE.*\"iwlwifi-3945-\"/#define IWL3945_FW_PRE \"lbm-iwlwifi-3945-\"/' drivers/net/wireless/iwlwifi/iwl-3945.h
sed -i 's/#define.*IWL4965_FW_PRE.*\"iwlwifi-4965-\"/#define IWL4965_FW_PRE \"lbm-iwlwifi-4965-\"/' drivers/net/wireless/iwlwifi/iwl-4965.c
sed -i 's/#define.*IWL5000_FW_PRE.*\"iwlwifi-5000-\"/#define IWL5000_FW_PRE \"lbm-iwlwifi-5000-\"/' drivers/net/wireless/iwlwifi/iwl-5000.c
sed -i 's/#define.*IWL5150_FW_PRE.*\"iwlwifi-5150-\"/#define IWL5150_FW_PRE \"lbm-iwlwifi-5150-\"/' drivers/net/wireless/iwlwifi/iwl-5000.c
sed -i 's/#define.*IWL6000_FW_PRE.*\"iwlwifi-6000-\"/#define IWL6000_FW_PRE \"lbm-iwlwifi-6000-\"/' drivers/net/wireless/iwlwifi/iwl-6000.c
