#!/bin/bash
#
# 
#
src="$HOME/git2/linux-2.6"
drm="$src/drivers/gpu/drm/"
rm -rf nouveau
mkdir nouveau nouveau/include
cp -rp "$drm"/Kconfig nouveau/
cp -rp "$drm"/Makefile nouveau/
cp -rp "$drm"/nouveau/ nouveau/
cp -rp "$drm"/ttm/ nouveau/
cp -rp "$drm"/*.[hc] nouveau/
cp -rp "$src"/include/drm/ nouveau/include

mkdir nouveau/include/linux
cp /home/apw/git2/linux-2.6/include/linux/list_sort.h nouveau/include/linux/
cp /home/apw/git2/linux-2.6/lib/list_sort.c nouveau/
