#!/bin/bash
#==============================================================================
# Remote build script (must reside in top-level directory of base directory.
#==============================================================================
cd $(dirname $0)
LOG="$(pwd)/build.log"
BPID=0
LPID=0
AUTOBUILD=0
BUILDTARGET="kernel"

#
# Might come from config file
#
STATUSFILE="$(pwd)/build-status"
CONCURRENCY_LEVEL=1
if [ -r build.cfg ]; then
	. build.cfg
fi

while [ $# -gt 0 ]; do
	case $1 in
		-a)
			AUTOBUILD=1
			;;
		-c|--concurrency)
			CONCURRENCY_LEVEL=$2
			shift
			;;
		-c*)
			CONCURRENCY_LEVEL=$(echo $1|cut -c3-)
			;;
		--lum)
			BUILDTARGET="lum"
			;;
		-*|--*)
			echo "Unknown option $1" >&2
			exit 1
			;;
	esac
	shift
done
export AUTOBUILD

if [ -d /usr/lib/ccache ]; then
	export PATH=/usr/lib/ccache:$PATH
	export CCACHE_DIR=$(pwd)/ccache

	echo "Using ccache in $CCACHE_DIR"
	test -d	 $CCACHE_DIR || mkdir $CCACHE_DIR
fi

function BuildLUM()
{
	local VER
	local NAME
	local HEADER
	local HEADERS

	VER=$(
		head -1 debian/changelog |
		sed 's/.*(\(.*\)).*$/\1/' |
		cut -d. -f1-3
	)
	HEADERS=$(ls -1 ../linux-headers-$VER-* | grep -v _all.deb)

	if [ -d headers ]; then
		echo "Removing old headers..."
		rm -rf headers
	fi
	echo "Extracting global headers..."
	dpkg-deb -x ../linux-headers-$VER_*_all.deb headers || return 1
	sleep 1

	for HEADER in $HEADERS; do
		NAME=$(echo $HEADER | cut -d- -f5 | cut -d_ -f1)
		echo "Building LUM for $NAME"
		dpkg-deb -x $HEADER headers
		fakeroot debian/rules clean || return 1
		fakeroot debian/rules \
			KDIR=$(pwd)/headers/usr/src/linux-headers-$VER-$NAME \
			binary-modules-$NAME
		if [ $? -ne 0 ]; then
			return 1
		fi
	done
	rm -rf headers
	sleep 1
}
	
function Cleanup()
{
	if ps hp$BPID >/dev/null 2>&1; then
		kill $BPID
	fi
	if ps hp$LPID >/dev/null 2>&1; then
		kill $LPID
	fi
	if [ "$1" != "0" ]; then
		echo "Failure($1)" >>$LOG
		echo "STATE=failed" >$STATUSFILE
	else
		rm -f $STATUSFILE
	fi
	wait
	exit 0
}
trap 'Cleanup 3' INT QUIT TRAP USR1 PIPE TERM

cat <<-ENDSTATUS >$STATUSFILE
STATE=building
BUILDTARGET=${BUILDTARGET}
PID=$$
ENDSTATUS

echo "${BUILDTARGET} build started $(date)" >$LOG

case "${BUILDTARGET}" in
	kernel)
		cd ubuntu-2.6
		fakeroot debian/rules clean >$LOG 2>&1 || Cleanup $?
		fakeroot debian/rules binary-headers \
			CONCURRENCY_LEVEL=$CONCURRENCY_LEVEL >>$LOG 2>&1 ||
			Cleanup $?
		fakeroot debian/rules binary-arch \
			CONCURRENCY_LEVEL=$CONCURRENCY_LEVEL >>$LOG 2>&1 &
		BPID=$!
		;;
	lum)
		cd ubuntu-2.6-lum
		BuildLUM >>$LOG 2>&1 &
		BPID=$!
		;;
	*)
		Cleanup 4
		exit 0
		;;
esac

tail -f $LOG &
LPID=$!

wait $BPID
Cleanup $?

exit 0
