#!/bin/bash
#==============================================================================
# This script handles the verbose output of the build status for LUM builds.
# It requires some variables to be preset by the build status, otherwise it
# will not work correctly.
#==============================================================================
DONE=""
WAIT=""
BUILD=""
for F in $FLAVOURS; do
	if [ "$(ls -1 $PKGPREFIX$F* 2>/dev/null)" != "" ]; then
		DONE="$DONE $F"
		continue
	fi
	if [ "$FLAVOUR" != "$F" ]; then
		WAIT="$WAIT $F"
		continue
	fi
	if [ -f "$DIR/debian/stamps/stamp-build-$F" ]; then
		BUILD="$F(packaging)"
		continue
	fi
	if [ -f "$DIR/debian/stamps/stamp-prepare-$F" ]; then
		BUILD="$F(building)"
		continue
	fi
	BUILD="$F(setup)"
done

if [ "$BUILD" = "" ]; then
	echo "Q:$WAIT"
else
	echo "Q: $BUILD$WAIT"
fi
echo "D:$DONE"

exit 0

