#!/bin/bash
#==============================================================================
# Cleanup script
#==============================================================================
STATUSFILE=$(dirname $0)/build-status
BRANCH="master"
DIR=""

while [ $# -ne 0 ]; do
	case $1 in
		-b|--branch)
			BRANCH="$2"
			shift
			;;
		-*|--*)
			echo "Unknown option <$1>!" >&2
			exit 1
			;;
		*)
			if [ "${DIR}" = "" ]; then
				DIR="$1"
			else
				echo "Too many arguments!" >&2
				exit 1
			fi
			;;
	esac
	shift
done

cd $(dirname $0)

if [ "${DIR}" = "" ]; then
	echo "Target directory not specified!" >&2
	exit 1
fi
if [ ! -d "${DIR}" ]; then
	echo "Target directory not found!" >&2
	exit 1
fi

if [ -f "${STATUSFILE}" ]; then
	. ${STATUSFILE}

	case "${STATE}" in
		failed)
			;;
		cleanup)
			echo "cleanup in progress, quitting"
			exit 1
			;;
		*)
			echo "Build in progress, quitting"
			exit 1
	esac
fi

echo "STATE=cleanup" >"${STATUSFILE}"

rm -f build.log *.udeb
if [ -d "${DIR}/.git" ]; then
	if [ "$(cd "${DIR}" && git-branch|grep "${BRANCH}")" = "" ]; then
		echo "Invalid branch <${BRANCH}>!" >&2
	else
		mv "${DIR}" "${DIR}.old"
		mkdir "${DIR}"
		if mv "${DIR}.old/.git" "${DIR}/"; then
			rm -rf "${DIR}.old"
		fi
		cd "${DIR}"
		git-checkout -f "${BRANCH}"
		cd - >/dev/null 2>&1
	fi
fi

rm ${STATUSFILE}

exit 0
