#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

# Cleanup the daily build
for which in \
	"$HOME/public_html/mainline/daily" \
	"$HOME/public_html/mainline/drm-next" \
	"$HOME/public_html/mainline/drm-intel-next" \
	"$HOME/public_html/mainline/drm-intel-fixes" \
	"$HOME/public_html/mainline/prestable"/*
do
	"$here/cleanup-daily-one" "$which"
done
	
exit 0
