#!/bin/bash

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

. "$here/lib-build"

master_tags="$master_state/upstream"
tags_list="$master_tags/TAGS"

# Ensure our master state exists.
mkdir -p "$master_tags"

# We are going to use the master linux build tree.
master_tree_select

# Pull in all trees containing tags we wish to build.
repo_remote_update_list $ubuntu_series linus 2.6.32.y.33.z linux-stable

#
# UPSTREAM TAGS: Find all the new upstream release tags.
#
git tag -l >"$tags_list.new"

diff "$tags_list" "$tags_list.new" | \
	awk '/>/ && $2 ~ /^v/ { print $2 }' | tac >"$tags_list.added"

# Commit the list.
mv "$tags_list.new" "$tags_list"

# Run the list.
while read commit
do
	"$here/cod-enqueue" "B" "$here/mainline-build" "$commit"
done <"$tags_list.added"

rm -f "$tags_list.added"
