#!/bin/bash

queue="$HOME/COD/queue"

count=`ls -1 "$queue" | wc -l`

for i in "$queue"/*
do
	read cmd args <"$i"
	cmd=`basename "$cmd"`
	echo "$cmd $args" | sed -r -e 's/([0-9a-f]{8})[0-9a-f]{32}/\1/g'
done
