#!/bin/bash
P="cod-crack-trigger"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

. "$here/lib-build"

master_tags="$master_state/upstream"
tags_list="$master_tags/TAGS"

# Ensure our master state exists.
mkdir -p "$master_tags"

# We are going to use the master linux build tree.
master_tree_select

#
# UPSTREAM COD: builds of upstream tree tips
#
repo_remote_update_list linus drm-2.6 drm-intel-danvet debloat-testing

refresh=1
date="`date +%F`"
while read branch abi base
do
	curr="$master_tags/$base"
	# Check for upstream crack of the day.
	tip=`git log --pretty=format:%H $branch^..$branch | head -1`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "branch<$branch> tip<$tip> prev<$prev>"

	if [ "$tip" != "" -a "$tip" != "$prev" ]; then
		# Commit the new tip.
		echo "$tip" >"$curr.new"
		mv -f "$curr.new" "$curr"

		if [ "$refresh" -eq 1 ]; then
			repo_remote_update_list $ubuntu_series
			refresh=0
		fi
		"$here/cod-enqueue" "C" \
			"$here/mainline-build" "$tip" "$abi" "$base" "$date"
	fi
done <<EOL
linus/master					999	daily
drm-2.6/drm-next				996	drm-next
drm-intel-danvet/drm-intel-next			997	drm-intel-next
drm-intel-danvet/drm-intel-nightly		994	drm-intel-nightly
debloat-testing/master				993	debloat-testing
EOL
# Also allocated
# 995: sconklin -- wayland
#
# NOTE: if you add a daily build above ensure it is recorded on the
# TopicBranches page, and also ensure you add it to the cleanup script.
