#!/bin/bash

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

master_main="$HOME/COD"

master_repo="/srv/kernel.ubuntu.com/git/ubuntu/"

#
# UBUNTU PRE-PROPOSED: tips of the ubuntu trees.
#
date=`date +%Y%m%d%H%M`
while read repo series branch
do
	current="${repo}_${series}_${branch}"
	curr="$master_main/preproposed/$current"
	branch="$series/$branch"

	# Add the upstream repos as needed.
	(
		if [ ! -d "$master_main/$repo" ]; then
			echo "*** creating initial repo ($repo) ..."
			mkdir -p "$master_main/$repo"
			cd "$master_main/$repo" && git init
		else
			cd "$master_main/$repo"
		fi
		series_repo=`echo "$repo" | sed -e "s/linux/ubuntu-$series/"`
		series_repo="$master_repo/$series_repo.git"
		if ! git remote | grep "$series" >/dev/null 2>&1; then
			echo "*** adding $series remote ($series_repo)..."
			git remote add "$series" "$series_repo"
		fi
		git fetch "$series"
	)

	# Find the first non-ignored commit, the first real change.
	tip=`cd "$master_main/$repo" && git log "$branch" | awk '
		BEGIN				{ sha1 = "" }
		/^ *UBUNTU: Bump ABI/		{ exit }
		/^commit /			{ if (sha1 != "") { exit };
						  sha1 = $2 }
		/^ *Ignore: *yes/		{ sha1 = "" }
		END				{ print sha1 }
	'`

	release=`cd "$master_main/$repo" && git log "$branch" | awk '
		/^commit /			{ sha1 = $2 }
		/^ *UBUNTU: *Ubuntu-2\.6\./	{ exit }
		END				{ print sha1 }
	'`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "repo<$repo> branch<$branch> tip<$tip> release<$release> prev<$prev>"

	if [ "$tip" != "$prev" ]; then
		# Commit the new tip.
		echo "$tip" >"$curr.new"
		mv -f "$curr.new" "$curr"

		if [ "$tip" != "$release" ]; then
			"$here/cod-enqueue" "A.preproposed-$current" \
				"$here/cod-preproposed" "$repo" "$series" \
					"$tip" "$date"
		else
			echo "tip represents release, nothing to do"
		fi
	fi
done <<EOL
linux natty master-next
linux-meta natty master
linux maverick master-next
linux-lbm maverick master
linux-meta maverick master
linux lucid master-next
linux-lbm lucid master
linux-meta lucid master
linux karmic master
linux-lbm karmic master
linux-meta karmic master
linux hardy master
linux-meta hardy master
EOL
