#!/bin/bash
#
# cod-enqueue <tag> <cmd> ...
#
# Enqueue the specified command for execution by the crack-of-the-day
# builder.
#
P="cod-enqueue"

queue="$HOME/COD/queue"
mkdir -p "$queue"

if [ "$#" -lt 2 ]; then
	echo "Usage: $P <priority A|B|C> <cmd> ..." 1>&2
	exit 1
fi
priority="$1"
shift

tag()
{
	cmd=`basename "$1"`
	shift
	echo "$cmd $@" | sed -r -e 's/([0-9a-f]{8})[0-9a-f]{32}/\1/g' -e 's/ /_/g'
}
tag=`tag "$@"`

time=`date +%s`
entry="$priority.$time.$tag.$$"

tmp="$queue/.$entry"

echo "$@" >"$tmp"

if ! mv "$tmp" "$queue/$entry"; then
	echo "$P: $tag -- enqueue failed" 1>&2
	exit 1
fi

echo "$P: $tag -- enqueued"
