#!/bin/bash
P="cod-prestable-trigger"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

. "$here/lib-build"

stated="$master_state/prestable"

# Ensure our master state exists.
mkdir -p "$stated"

# We are going to use the master linux build tree.
master_tree_select

#
# UPSTREAM COD: builds of upstream tree tips
#
repo_remote_update_list ubuntu-stable

refresh=1
date="`date +%F`"

abi=999

git branch -r | grep '^  ubuntu-stable/linux-' | \
while read branch
do
	base=`echo "$branch" | sed -e 's@^ubuntu-stable/@@'`
	curr="$stated/$base"
	outdir="prestable/$base"
	tip=`git log --pretty=format:%H $branch^..$branch | head -1`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "branch<$branch> tip<$tip> prev<$prev>"

	if [ "$tip" != "" -a "$tip" != "$prev" ]; then
		# Commit the new tip.
		echo "$tip" >"$curr.new"
		mv -f "$curr.new" "$curr"

		if [ "$refresh" -eq 1 ]; then
			repo_remote_update_list $ubuntu_series
			refresh=0
		fi
		"$here/cod-enqueue" "C" \
			"$here/mainline-build" "$tip" "$abi" "$outdir" "$date"
	fi
done
