#!/bin/bash
#
# cod-incoming-publish -- pull publishable images out of incoming and 
# install them, upload them, and/or announce them as required.
#
P="cod-incoming-publish"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

incoming="$HOME/incoming"
lock_tmp="$incoming/.LOCK-$$"
lock="$incoming/.LOCK"

outgoing="$HOME/public_html/mainline"

# One at a time please...
mkdir -p "$incoming"

echo "$$" >"$lock_tmp"
while ! ln "$lock_tmp" "$lock" 2>/dev/null
do
    echo "$P: incoming locked ... waiting" 1>&2
    sleep 20
done
rm -f "$lock_tmp"

# Pull out any published images ...
(cd "$incoming/mainline" && find . -name COMMIT) | \
while read commit
do
	build=`dirname "$commit"`
	build=${build#./}

	echo "$P: $build: publishing ..."
	if [ -d "$outgoing/$build" ]; then
		echo "$P: $build: result already published"
		rm -rf "$outgoing/$build"
	fi
	announce=0
	mv "$incoming/mainline/$build" "$outgoing/$build" && \
	{
		case "$build" in
		*/*)	;;
		*)	announce=1 ;;
		esac
	}
	if [ "$announce" -eq 1 ]; then
		echo "$P: $build: announcing ..."
		"$here/mainline-announce" `cat "$outgoing/$build/COMMIT"` "$build"
	fi
done

# We are done.
rm -f "$lock"
