#!/bin/bash

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

master_main="$HOME/mainline"
master_tree="$master_main/build"

master_tags="$master_main/upstream"
tags_list="$master_tags/TAGS"

master_repo="/srv/kernel.ubuntu.com/git/ubuntu/"

# Build us a master tree if we do not have one.
if [ ! -d "$master_tree" ]; then
	echo "*** creating primary build tree ..."
	mkdir -p "$master_tree"
	cd "$master_tree"
	git init
else
	cd "$master_tree"
fi

# Get an updated linus kernel, we always need that.
if ! git remote show -n linus >/dev/null 2>&1; then
	echo "*** adding linus remote ..."
	git remote add linus \
		git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6.git
fi

# Pull in all the supported series ...
for series in dapper hardy intrepid jaunty karmic lucid maverick
do
	series_repo="$master_repo/ubuntu-$series.git"
	if ! git remote show -n "$series" >/dev/null 2>&1; then
		echo "*** adding $series remote ..."
		git remote add "$series" "$series_repo"
	fi
done

# We need to pre-fetch linus as we may add new remotes based on
# its current tip.
git fetch linus

# Work out which stable branch we might need.
current=`git describe --tags linus/master`
current="${current%%-*}"
current="${current#v2.6.}"

let wanted=32
while [ "$wanted" -lt "$current" ]; do
	stable="2.6.${wanted%.*}.y"
	
	if ! git remote show -n "$stable" >/dev/null 2>&1; then
		echo "*** adding $stable remote ..."
		git remote add "$stable" \
			git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-$stable.git
	fi
	let "wanted=$wanted+1"
done

# Update all the remotes in this tree.
git remote | \
while read remote
do
	echo "*** fetching $remote ..."
	git fetch "$remote"
done

#
# UBUNTU PRE-PROPOSED: tips of the ubuntu trees.
#
"$here/cod-preproposed-trigger"

#
# UPSTREAM TAGS: Find all the new upstream release tags.
#
git tag -l >"$tags_list.new"

diff "$tags_list" "$tags_list.new" | \
	awk '/>/ && $2 ~ /^v/ { print $2 }' | tac >"$tags_list.added"

# Commit the list.
mv "$tags_list.new" "$tags_list"

# Run the list.
while read commit
do
	"$here/cod-enqueue" "B.mainline-$commit" \
		"$here/mainline-build" "$commit"
done <"$tags_list.added"

rm -f "$tags_list.added"

#
# UPSTREAM COD: builds of upstream tree tips
#
while read current branch abi base
do
	curr="$master_tags/$current"
	# Check for upstream crack of the day.
	tip=`git log --pretty=format:%H $branch^..$branch | head -1`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "branch<$branch> tip<$tip> prev<$prev>"

	if [ "$tip" != "$prev" ]; then
		# Commit the new tip.
		echo "$tip" >"$curr.new"
		mv -f "$curr.new" "$curr"

		"$here/cod-enqueue" "C.cod-$current" \
			"$here/mainline-build" "$branch" "$abi" "$base"
	fi
done <<EOL
LINUS		linus/master			999	daily
DRM-INTEL-NEXT	drm-intel/drm-intel-next	997	drm-intel-next
DRM-NEXT	drm-2.6/drm-next		996	drm-next
EOL
# Also allocated
# 995: sconklin -- wayland
