#! /bin/bash

P="build-mainline-crack"

if [ "$#" -ne 3 ]; then
	echo "Usage: $P <commit> <series> <abinum>" 1>&2
	exit 1
fi

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"
series="$2"
abinum="$3"

echo "*** BUILDING CRACK: commit:$1 series:$2 ..."

build_release="hardy"

long=`git describe "$commit"`
if [ "$?" -ne 0 ]; then
	echo "$P: $commit: invalid commit" 1>&2
	exit 1
fi
case "$long" in
v*-*[0-9]-g*)
	full_version="${long#v}"
	full_version="${full_version%-*}"
	full_version="${full_version%-*}"
	;;
v*)
	full_version="${long#v}"
	;;
*)
	echo "$P: $commit: mapped to '$long' unable to process" 1>&2
	exit 1
esac

# Crack of the day is always ABI -999 or similar.
upload=`date +%Y%m%d%H%M`

# The base version is always the first X.Y.Z part of the version number.  If we
# do not maintain this then the modules directory will not match uname -r.
version=`echo "$full_version" | sed -e 's/\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`

#release=`pwd`
#release=${release#*/ubuntu-}
#release=${release%-build}

echo "full_version<$full_version>"
echo "version<$version>"
echo "long<$long>"
echo "abinum<$abinum>"

# NOTE: a - in the branch name seems to be causing issues.
branch="BUILD.$abinum"
branch=`echo "$branch" | sed -e 's/-/./g'`

# Ensure we get the uptodate machinary.
git fetch "$series"
git checkout -f "$series/master"
git branch -D "$branch"

rm -rf .dotest

#
# Checkout the source at the specified version.
#
git checkout -b "$branch" "$long" -- || exit 1

# Report the head for posterity.
echo "vvv - build head"
git log -1 HEAD
echo "^^^ - build head"

#
# Pull in the packaging from the head of our tree.
#
git checkout "$series/master" -- debian
git checkout "$series/master" -- debian.master
git commit -a -m "base packaging"

#
# ALL: allow us to default new config options.
#
## XXX: git am -C0 "$here/0001-disable-udebs.patch"

if [ -d "$here/patches.$series" ]; then
	echo "*** applying patches for series:$series ..."
	git am -C1 "$here/patches.$series"/*
fi

#
# Rebuild the changelog.
#
for debian in "debian.master" "debian"
do
	[ -d "$debian" ] && break
done 
changelog="$debian/changelog"
rm -f "$changelog"
EDITOR=":" dch -v "${version}-$abinum.$upload" --distribution "$series" \
	--package linux --create -c "$changelog" </dev/null
sed -e "s/\* .*/* Crack of the day commit: $long/" \
	<"$changelog" >"$changelog.new"
mv -f "$changelog.new" "$changelog"
git commit -a -m "debian changelog"

#
# Default any new configuration options.
#
if [ -f "$here/config.$series" ]; then
        cp "$here/config.$series" "$debian/config/OVERRIDES"
fi
BUILD_CONFIG_OVERRIDE="$here/config.$series"
dchroot --directory=`pwd` -c "$build_release" \
	"BUILD_CONFIG_OVERRIDE='$BUILD_CONFIG_OVERRIDE' fakeroot debian/rules defaultconfigs"
##BUILD_CONFIG_OVERRIDE='$BUILD_CONFIG_OVERRIDE' schroot --directory=`pwd` -c "$build_release-i386" fakeroot debian/rules defaultconfigs
git commit -a -m "default configs"

#
# Disable the ABI, module, and aliases checks.
#
for i in debian/scripts/*-check debian.master/scripts/*-check
do
	if [ -f "$i" ]; then
		cat - <<EOM >"$i"
#!/bin/sh
exit 0
EOM
		chmod 755 "$i"
	fi
done

git commit -a -m "fix up build checks"

#
# Build the source package.
#
##dpkg-buildpackage -S -rfakeroot -I.git -I.gitignore -i'\.git.*' -sa

dchroot --directory=`pwd` -c "$build_release" \
        "fakeroot debian/rules clean"
dchroot --directory=`pwd` -c "$build_release" \
        "fakeroot debian/rules no_dumpfile=1 do_linux_source_content=true binary-indep"
dchroot --directory=`pwd` -c "$build_release" \
        "fakeroot debian/rules clean"
dchroot --directory=`pwd` -c "$build_release" \
        "fakeroot debian/rules no_dumpfile=1 binary-generic"
linux32 dchroot --directory=`pwd` -c "$build_release-i386" \
        "fakeroot debian/rules clean"
linux32 dchroot --directory=`pwd` -c "$build_release-i386" \
        "fakeroot debian/rules no_dumpfile=1 binary-generic"
