#!/usr/bin/python
import smtplib
import sys
import os

commit = sys.argv[1]

# Add the From: and To: headers at the start!
msg  = """From: Mainline Builds <kernel-team@lists.ubuntu.com>\r
To: Kernel Team <kernel-team@lists.ubuntu.com>\r
Reply-to: Kernel Team <kernel-team@lists.ubuntu.com>\r
Subject: Mainline Build %(commit)s\r
\r
The mainline build for %(commit)s is now complete and available at the URL\r
below:\r
\r
    http://kernel.ubuntu.com/~%(user)s/mainline/%(commit)s/\r
\r
See the CHANGES file for the list of changes from the previous version:\r
\r
    http://kernel.ubuntu.com/~%(user)s/mainline/%(commit)s/CHANGES\r
\r
Note that these builds do not contain any Ubuntu specific patches and\r
are not supported.\r
\r
Kernel Team\r
""" % ({'commit': commit, 'user': os.environ['USER']})

print msg;

server = smtplib.SMTP('lists.ubuntu.com')
server.set_debuglevel(0)
server.sendmail('apw@canonical.com',
		'kernel-team@lists.ubuntu.com', msg)
server.quit()
