#!/bin/bash

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

master_main="$HOME/COD"
master_tree="$master_main/linux"

master_tags="$master_main/upstream"
tags_list="$master_tags/TAGS"

#master_repo="/srv/kernel.ubuntu.com/git/ubuntu"
master_repo="git://kernel.ubuntu.com/ubuntu"

# Build us a master tree if we do not have one.
if [ ! -d "$master_tree" ]; then
	echo "*** creating primary build tree ..."
	mkdir -p "$master_tree"
	cd "$master_tree"
	git init
else
	cd "$master_tree"
fi

# Get an updated linus kernel, we always need that.
if ! git remote | grep linus >/dev/null 2>&1; then
	echo "*** adding linus remote ..."
	git remote add linus \
		git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6.git
fi

# Pull in all the supported series ...
for series in hardy lucid maverick natty oneiric
do
	series_repo="$master_repo/ubuntu-$series.git"
	if ! git remote | grep "$series" >/dev/null 2>&1; then
		echo "*** adding $series remote ..."
		git remote add "$series" "$series_repo"
	fi
	echo "*** fetching $series remote ..."
	git fetch "$series" || true
done

# Special trees we also need but we cannot calculate from the version number.
while read remote url
do
	if ! git remote | grep "$remote" >/dev/null 2>&1; then
		echo "*** adding $remote remote ..."
		git remote add "$remote" "$url"
	fi
done <<EOL
2.6.32.y.33.z git://git.kernel.org/pub/scm/linux/kernel/git/smb/linux-2.6.32.y-drm33.z.git
linux-stable git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
EOL

# Update all the remotes in this tree.
git remote | \
while read remote
do
	echo "*** fetching $remote ..."
	git fetch "$remote" || true
done

#
# UBUNTU PRE-PROPOSED: tips of the ubuntu trees.
#
"$here/cod-preproposed-trigger"

#
# UPSTREAM TAGS: Find all the new upstream release tags.
#
git tag -l >"$tags_list.new"

diff "$tags_list" "$tags_list.new" | \
	awk '/>/ && $2 ~ /^v/ { print $2 }' | tac >"$tags_list.added"

# Commit the list.
mv "$tags_list.new" "$tags_list"

# Run the list.
while read commit
do
	"$here/cod-enqueue" "B" "$here/mainline-build" "$commit"
done <"$tags_list.added"

rm -f "$tags_list.added"

#
# UPSTREAM COD: builds of upstream tree tips
#
while read remote url
do
	if ! git remote | grep "$remote" >/dev/null 2>&1; then
		echo "*** adding $remote remote ..."
		git remote add "$remote" "$url"
	fi
	echo "*** fetching $remote remote ..."
	git fetch "$remote" || true
done <<EOL
drm-2.6 git://git.kernel.org/pub/scm/linux/kernel/git/airlied/drm-2.6
drm-intel git://git.kernel.org/pub/scm/linux/kernel/git/ickle/drm-intel
debloat-testing git://git.infradead.org/debloat-testing.git
EOL

date="`date +%F`"
while read current branch abi base
do
	curr="$master_tags/$current"
	# Check for upstream crack of the day.
	tip=`git log --pretty=format:%H $branch^..$branch | head -1`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "branch<$branch> tip<$tip> prev<$prev>"

	if [ "$tip" != "$prev" ]; then
		# Commit the new tip.
		echo "$tip" >"$curr.new"
		mv -f "$curr.new" "$curr"

		"$here/cod-enqueue" "C" \
			"$here/mainline-build" "$tip" "$abi" "$base" "$date"
	fi
done <<EOL
LINUS		linus/master			999	daily
DRM-INTEL-NEXT	drm-intel/drm-intel-next	997	drm-intel-next
DRM-NEXT	drm-2.6/drm-next		996	drm-next
DRM-INTEL-NEXT-PROPOSED	drm-intel/drm-intel-next-proposed 994 drm-intel-next-proposed
DEBLOAT-TESTING	debloat-testing/master		993	debloat-testing
EOL
# Also allocated
# 995: sconklin -- wayland
#
# NOTE: if you add a daily build above ensure it is recorded on the
# TopicBranches page, and also ensure you add it to the cleanup script.
