#!/bin/bash
P="ssh-mainline-publish"

#echo "$SSH_ORIGINAL_COMMAND" 1>&2
case "$SSH_ORIGINAL_COMMAND" in
"rsync --server -vlogDtpre.iLsf . incoming/")   ;;
*)
	echo "$P: invalid command" 1>&2
	exit 1
esac

# Belt and braces
case "$SSH_ORIGINAL_COMMAND" in
*[\;\|\<\>]*)
	echo "$P: invalid command" 1>&2
	exit 1
	;;
esac

incoming="$HOME/incoming"
lock_tmp="$incoming/.LOCK-$$"
lock="$incoming/.LOCK"

# One at a time please...
mkdir -p "$incoming"

echo "$$" >"$lock_tmp"
while ! ln "$lock_tmp" "$lock" 2>/dev/null
do
    echo "$P: incoming locked ... waiting" 1>&2
    sleep 20
done
rm -f "$lock_tmp"

# Perform the sync ...
$SSH_ORIGINAL_COMMAND

# We are done.
rm -f "$lock"
