# Display drivers

display-objs				:= display-sysfs.o

obj-$(CONFIG_DISPLAY_SUPPORT)		+= display.o

obj-$(CONFIG_CH7025_COMPOSITE)  += ch7025_composite.o
obj-$(CONFIG_KG2_ANX7150) += kg2
obj-$(CONFIG_KG2_ANX7150) += ANX7150

