#!/bin/bash
CDIR=$(cd $(dirname $0); pwd)
. $CDIR/build-common

BRANCH="master"
TARGETS=""
while [ $# -gt 0 ]; do
	case $1 in
		-b|--branch)
			BRANCH="$2"
			shift
			;;
		-*|--*)
			echo "Unknown option <$1>!" >&2
			exit 1
			;;
		*)
			TARGETS="$TARGETS $1"
			;;
	esac
	shift
done

if [ "${TARGETS}" = "" ]; then
	echo "Usage: $(basename $0) [<options>] <system|group> [...]"
	exit 1
fi

GetDistroEnvironment "${DIST}" || exit 1

if [ ! -d ${SRCDIR}/.git ]; then
	echo "${SRCDIR} is not a repository!" >&2
	exit 1
fi
cd $SRCDIR

if [ "$(git branch|grep "${BRANCH}")" = "" ]; then
	echo "No branch <${BRANCH}> found!" >&2
	exit 1
fi

function AddSummary()
{
	local LINE

	LINE="$(printf "%-15s %s\n" $SYSNAME "$@")"
	if [ "$SUMMARY" != "" ]; then
		SUMMARY="$(echo -e "$SUMMARY\n$LINE")"
	else
		SUMMARY="$LINE"
	fi
}

function PrepareHost()
{
	if $VERBOSE; then
		echo "  Source:     ${SRCDIR}"
		echo "  Sending to: ${HOST}:${BUILDDIR}"
	fi

	# Look up the origin URL and see if that is a kernel repo.
	URL=`git config remote.origin.url`
	case "$URL" in
	*kernel.ubuntu.com/*|*zinc.ubuntu.com/*)
		URL=`echo "$URL" | sed -e 's@.*/\([^/]*/[^/]*\)$@\1@'`
		URL="git://kernel.ubuntu.com/$URL"
		;;
	*)	URL='' ;;
	esac

	cat <<-EOD | ssh ${HOST} 2>/dev/null
	if [ ! -d $BUILDDIR ]; then
		echo "  remote: creating $BUILDDIR"
		mkdir -p $BUILDDIR
		if [ \$? -ne 0 ]; then
			echo "  remote: failed to create directory!"
			exit 1
		fi
	fi
	cd "${BUILDDIR}" || exit 1
	if [ ! -d "${BUILDDIR}/.git" ]; then
		echo "  remote: creating empty git repos."
		git init
		if [ \$? -ne 0 ]; then
			echo "  remote: failed to initialize git!"
			exit 1
		fi
	fi
	if [ "$USE_DC" = 'yes' -a  "$URL" != '' ]; then
		# Check if we have our upstream repository.
		if ! git remote show -n "origin" >/dev/null 2>&1; then
			echo "  remote: adding origin remote to DC"
			git remote add "origin" "$URL"
		fi
		# Get as many objects from the upstream repo as possible.
		echo "  remote: updating from DC"
		git fetch "origin"
	fi
	EOD
	if [ $? -ne 0 ]; then
		AddSummary "[remote git init failed]"
		return 1
	fi

	echo "  local: sending status scripts..."
	scp -q $CDIR/target-scripts/run-* ${HOST}:${BASEDIR}

	echo "  local: using git to push..."
	cd "${SRCDIR}"
	git push --tags --force ${HOST}:${BUILDDIR} ${BRANCH}
	if [ $? -ne 0 ]; then
		AddSummary "[git push failed]"
		return 1
	fi

	echo "  ${HOST}: cleaning up build area ..."
	ssh ${HOST} ${BASEDIR}/run-clean --branch ${BRANCH} \
		$(basename ${BUILDDIR})
}

SUMMARY=""
for TARGET in $(ExpandHostGroups $TARGETS); do
	echo "$TARGET ..."
	GetHostEnvironment ${TARGET} 2>/dev/null
	if [ $? -ne 0 ]; then
		SYSNAME="$TARGET"
		AddSummary "[not configured]"
		continue
	fi
	status=$($CDIR/build-check --dist ${DIST} ${TARGET})
	if [ $? -ne 0 ]; then
		AddSummary "[$status]"
		continue
	fi

	for i in $(QueryChroots ${HOST}); do
		if [ "$i" = "${CHROOT}" ]; then
			break
		fi
	done
	if [ "$i" != "${CHROOT}" ]; then
		AddSummary "[no chroot found for $DIST]"
		continue
	fi
	PrepareHost && AddSummary "[OK]"
done

echo
echo "Summary:"
echo "$SUMMARY"

