#!/bin/bash

export BUILD_DIST_PRINTED=1
. $(dirname $0)/build-common

if [ "$1" = "" ]; then
        echo "Usage: $(basename $0) <system>"
        exit 1
fi

GetHostEnvironment $1 || exit 1

cat <<EOD | ssh -oConnectTimeout=15 $HOST 2>/dev/null
if [ ! -f "$BUILDING" ] ; then
	exit 1
fi
PID=0
. $BUILDING

case "\$STATE" in
	cleanup)
		exit 2
		;;
	failed)
		exit 3
		;;
	*)
		if ps hp\$PID >/dev/null 2>&1; then
			exit 0
		fi
		exit 3
esac

exit 4
EOD

case $? in
	0)
		echo "building"
		;;
	1)
		echo "idle"
		exit 0
		;;
	2)
		echo "cleanup in progress"
		;;
	3)
		echo "idle (last build failed)"
		exit 0
		;;
	4)
		echo "unexpected status"
		;;
	*)
		echo "${HOST} is offline"
		;;
esac

exit 1
