#!/bin/bash
if [ "${UBUILDDIR}" = "" ]; then
	CONFDIR="${HOME}/.ubuild"
else
	CONFDIR="${UBUILDDIR}"
fi
if [ ! -d "${CONFDIR}" ]; then
	mkdir "${CONFDIR}"
fi
. $(dirname $0)/build-common

if [ ! -f "${CONFDIR}/config" ]; then
	cat <<-EOD >"${CONFDIR}/config"
	# DIST: Default distribution
	DIST="$DIST"
	EOD
fi

if [ ! -d "${CONFDIR}/distros" ]; then
	mkdir "${CONFDIR}/distros"
fi
for distro in dapper hardy intrepid jaunty karmic lucid; do
	if [ ! -f "${CONFDIR}/distros/${distro}" ]; then
		echo "Creating distro(${distro})"
		cat <<-EOD >"${CONFDIR}/distros/${distro}"
		# Where to find sources for that disto
		#SRCDIR=$HOME/ubuntu-$distro
		PKGNAMES=(
		 	kernel
		 	meta
		)
		PKGDIRS=(
		 	$HOME/ubuntu-$distro/kernel
		 	$HOME/ubuntu-$distro/meta
		)	
		EOD
	fi
done

if [ ! -d "${CONFDIR}/groups" ]; then
	mkdir "${CONFDIR}/groups"
fi
if [ ! -f "${CONFDIR}/groups/default" ]; then
	cat <<-EOD >"${CONFDIR}/groups/default"
	amd64
	i386
	sparc
	powerpc
	EOD
fi
if [ ! -f "${CONFDIR}/groups/autobuild" ]; then
	cat <<-EOD >"${CONFDIR}/groups/autobuild"
	ronne-i386
	ronne-amd64
	davis
	faure
	halley
	wongi
	rimu
	EOD
fi

if [ ! -d "${CONFDIR}/hosts" ]; then
	mkdir "${CONFDIR}/hosts"
fi
for host in davis faure halley ronne; do
	if [ ! -f "${CONFDIR}/hosts/${host}" ]; then
		echo "Creating host ${host}..."
		$(dirname $0)/build-create-host ${host}.ubuntu.com
	fi
done

