#!/bin/bash
. $(dirname $0)/build-common

if [ "$1" = "" ]; then
	echo "Usage: $0 <system>"
	exit 1
fi

GetHostEnvironment "$1"
status="$($(dirname $0)/build-check ${SYSNAME})"

if [ "$status" = "building" ]; then
	ssh -t ${HOST} screen -r
else
	echo "${SYSNAME}: $status"
fi
