#!/bin/bash
function ScriptUsage()
{
	echo "    Usage: $(basename $0) [<options>] <system> [...]"
}

function ScriptSpecificHelp()
{
	echo
}

. $(dirname $0)/build-common

if [ "$1" = "" ]; then
	ScriptUsage
	exit
fi

GetDistroEnvironment $DIST || exit
GetHostEnvironment $1 || exit

cat <<EOD
SYSNAME:   $SYSNAME
HOST:      $HOST
HOSTARCH:  $HOSTARCH
ARCH:      $ARCH
ARCHS:     $ARCHS
BASEDIR:   $BASEDIR
BUILDING:  $BUILDING
BUILDDIR:  $BUILDDIR
CHROOTCMD: $CHROOTCMD
CHROOTS:   $(QueryChroots $HOST)
SRCDIR:    $SRCDIR
EOD

exit 0
