#!/bin/bash
#==============================================================================
# Author: Stefan Bader <stefan.bader@canonical.com>
# Copyright (C) 2010
#
# This script is distributed under the terms and conditions of the GNU General
# Public License, Version 3 or later. See http://www.gnu.org/copyleft/gpl.html
# for details.
#==============================================================================
PrintUsage() {
	echo "Usage $(basename $0): [options] <series> <target> <path>"
	echo
	echo -n "<series>: Name of the distribution series you want to add a"
	echo " target for."
	echo "<target>: Under what name the target should be added."
	echo "<path>:   Where is the git repository for that target located."
	echo
}

FORCE=false
CONFIGDIR="$HOME/.ubuild"
while [ $# -gt 0 ]; do
	case $1 in
		-c|--config)
			CONFIGDIR="$2"
			shift
			;;
		-h|--help)
			PrintUsage
			exit 0
			;;
		-*|--*)
			PrintUsage
			exit 1
			;;
		*)
			if [ "$SERIES" = "" ]; then
				SERIES="$1"
			elif [ "$TARGET" = "" ]; then
				TARGET="$1"
			elif [ "$TARGETDIR" = "" ]; then
				TARGETDIR="$1"
			else
				PrintUsage
				exit 1
			fi
			;;
	esac
	shift
done

if [ "$TARGETDIR" = "" ]; then
	PrintUsage
	exit 1
fi
if [ ! -d "$TARGETDIR" ]; then
	echo "$TARGETDIR is not a directory" >&2
	exit 1
fi
if [ ! -d "$TARGETDIR/.git" ]; then
	echo "$TARGETDIR is not a git repository" >&2
	exit 1
fi
if [ ! -d "$CONFIGDIR/distros" ]; then
	echo "Subdirectory distros not found in $CONFIGDIR" >&2
	exit 1
fi
if [ -r "$CONFIGDIR/distros/$SERIES" ]; then
	. "$CONFIGDIR/distros/$SERIES"
fi
N=0
for T in ${PKGNAMES[*]}; do
	if [ "$T" = "$TARGET" ]; then
		break
	fi
	let "N++"
done
PKGNAMES[$N]="$TARGET"
PKGDIRS[$N]="$TARGETDIR"

(
	echo "# Where to find sources for that series"
	if [ "$SRCDIR" != "" ]; then
		echo "SRCDIR=$SRCDIR"
		echo
	fi
	echo "PKGNAMES=("
	for T in ${PKGNAMES[*]}; do
		echo "	$T"
	done
	echo ")"
	echo "PKGDIRS=("
	for T in ${PKGDIRS[*]}; do
		echo "	$T"
	done
	echo ")"
) >"$CONFIGDIR/distros/$SERIES"

exit 0
