#!/bin/bash
#
# This script builds all releases
#
CDIR="`dirname $0`"
. $CDIR/ukb.conf
. $CDIR/../chroot-setup/scripts/chroot-defs.conf

usage()
{
	echo $0 --branch=BRANCH [--bdir=BUILD_DIR] [--clean]
	echo ex: $0 --branch=master-next
	exit 1
}

while [ $# -ne 0 ]; do
	case $1 in
		--branch=*)
			BRANCH="--branch=$(echo $1|cut -d= -f2)"
			;;
		--bdir=*)
			BDIR="--bdir=$(echo $1|cut -d= -f2)"
			;;
		--clean)
			CLEAN="--clean"
			;;
		--help)
			usage
			;;
		*)
			echo Unknown option \'$1\`
			usage
			;;
	esac
	shift
done

if [ -z "$BRANCH" ]
then
	echo --branch cannot be empty.
	usage
fi

for i in "${releases[@]}"
do
	echo release $i
	if not_expired_release $i
	then
		if ! $CDIR/ukb-make-release --release=$i $BRANCH $BDIR $CLEAN 
		then
			exit 1
		fi
	fi
done

exit 0

