#!/bin/bash
#
# This script builds all releases
#
CDIR="`dirname $0`"
. $CDIR/ukb.conf
. $CDIR/../chroot-setup/scripts/chroot-defs.conf

usage()
{
	echo $0 --branch=BRANCH [--bdir=BUILD_DIR] [--clean]
	echo ex: $0 --branch=master-next
}

while [ $# -ne 0 ]; do
	case $1 in
		--branch=*)
			BRANCH="--branch=$(echo $1|cut -d= -f2)"
			;;
		--bdir=*)
			BDIR="--bdir=$(echo $1|cut -d= -f2)"
			;;
		--clean)
			CLEAN="--clean"
			;;
		--help)
			usage
			;;
		*)
			echo Unknown option \'$1\`
			usage
			;;
	esac
	shift
done

for i in "${releases[@]}"
do
	if ! $CDIR/ukb-make-release --release=$i $BRANCH $BDIR $CLEAN 
	then
		exit
	fi
done

case $HOST_ARCH in
	amd64)
		for i in i386 amd64 armel
		do
			if ! $CDIR/ukb-make --arch=$i $REPO $RELEASE $BRANCH $BDIR $CLEAN
			then
				exit 1
			fi
		done
		;;
	*)
		$CDIR/ukb-make --arch=$HOST_ARCH $REPO $RELEASE $BRANCH $BDIR $CLEAN
		;;
esac

exit 0

