#!/bin/bash
#
# devel-config-summary-report -- generate a configuration summary for UDS
#
P="$0"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 3 ]; then
	echo "Usage: $P <format> <current series> <next series>" 1>&2
	exit 1
fi
format="$1"
current="$2"
next="$3"

"$here/lib-config/devel-config-compare" "$format" "$next/CONFIGS-info" "$next/CONFIGS"
"$here/lib-config/devel-config-experimental-compare" "$format" DANGEROUS "$current/CONFIGS-info" "$next/CONFIGS-info" "$next/CONFIGS"
"$here/lib-config/devel-config-experimental-compare" "$format" EXPERIMENTAL "$current/CONFIGS-info" "$next/CONFIGS-info" "$next/CONFIGS"
"$here/lib-config/devel-config-experimental-compare" "$format" STAGING "$current/CONFIGS-info" "$next/CONFIGS-info" "$next/CONFIGS"
"$here/lib-config/devel-config-new-compare" "$format" "$current/CONFIGS-defaults" "$next/CONFIGS-defaults" "$next/CONFIGS-experimental" "$next/CONFIGS-info" "$next/CONFIGS"
