#!/bin/bash

stub=debian/control.d/flavour-control.stub
vars=$1

# Defaults
section_image=base
section_headers=devel

. $vars

flavour=$(basename $vars | sed 's/.*\.//')
# Custom is a little different
if [ "$flavour" = "vars" ]; then
	flavour=$(basename `dirname $vars`)
fi

cat $stub | grep -v '^#' | sed			\
	-e "s#FLAVOUR#$flavour#g"		\
	-e "s#DESC#$desc#g"			\
	-e "s#ARCH#$arch#g"			\
	-e "s#=PROVIDES=#$provides#g"		\
	-e "s#SECTION_IMAGE#$section_image#g"
