snd-hda-intel-y := \
	hda_intel.o \
	hda_proc.o \
	hda_codec.o \
	hda_generic.o \
	patch_realtek.o \
	patch_cmedia.o \
	patch_sigmatel.o \
	patch_analog.o \
	patch_si3054.o \
	patch_atihdmi.o \
	patch_conexant.o \
	patch_via.o

obj-m += snd-hda-intel.o

EXTRA_CFLAGS := -DCONFIG_SND_HDA_GENERIC
